package org.openmetadatainitiative.openminds.v5.computation.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface ModelValidationInput extends Entity {
   Reference<? extends ModelValidationInput> getReference();

   class Deserializer extends ByTypeDeserializer<ModelValidationInput> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.v5.core.data.LocalFile.class, org.openmetadatainitiative.openminds.v5.computation.ValidationTestVersion.class, org.openmetadatainitiative.openminds.v5.core.data.File.class, org.openmetadatainitiative.openminds.v5.core.data.FileBundle.class, org.openmetadatainitiative.openminds.v5.core.products.ModelVersion.class, org.openmetadatainitiative.openminds.v5.core.products.SoftwareVersion.class);
        }
    }
    
}