package org.openmetadatainitiative.openminds.v5.computation.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface ServiceDeploymentUses extends Entity {
   Reference<? extends ServiceDeploymentUses> getReference();

   class Deserializer extends ByTypeDeserializer<ServiceDeploymentUses> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.v5.computation.WorkflowRecipeVersion.class, org.openmetadatainitiative.openminds.v5.core.products.DatasetVersion.class, org.openmetadatainitiative.openminds.v5.core.products.MetaDataModelVersion.class, org.openmetadatainitiative.openminds.v5.core.products.ModelVersion.class, org.openmetadatainitiative.openminds.v5.core.miscellaneous.WebResource.class, org.openmetadatainitiative.openminds.v5.SANDS.atlas.AnatomicalAtlasVersion.class, org.openmetadatainitiative.openminds.v5.SANDS.atlas.CommonCoordinateFrameworkVersion.class);
        }
    }
    
}