package org.openmetadatainitiative.openminds.v5.core.products.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface SoftwareVersionScope extends Entity {
   Reference<? extends SoftwareVersionScope> getReference();

   class Deserializer extends ByTypeDeserializer<SoftwareVersionScope> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.v5.controlledTerms.AnalysisTechnique.class, org.openmetadatainitiative.openminds.v5.controlledTerms.ContributionType.class, org.openmetadatainitiative.openminds.v5.controlledTerms.DataType.class, org.openmetadatainitiative.openminds.v5.controlledTerms.ExperimentalApproach.class, org.openmetadatainitiative.openminds.v5.controlledTerms.OperationalApproach.class, org.openmetadatainitiative.openminds.v5.controlledTerms.SoftwareApplicationCategory.class, org.openmetadatainitiative.openminds.v5.controlledTerms.SoftwareFeature.class, org.openmetadatainitiative.openminds.v5.controlledTerms.Technique.class, org.openmetadatainitiative.openminds.v5.controlledTerms.TermSuggestion.class);
        }
    }
    
}