package org.openmetadatainitiative.openminds.v5.specimenPrep.device;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.v5.specimenPrep.device.intf.SlicingDeviceContribution;
import org.openmetadatainitiative.openminds.v5.specimenPrep.device.intf.SlicingDeviceType;


import static org.openmetadatainitiative.openminds.v5.specimenPrep.device.SlicingDevice.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class SlicingDevice extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.V5.Entity, org.openmetadatainitiative.openminds.v5.core.products.intf.SetupHasPart{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/SlicingDevice";

    @JsonIgnore
    public Reference<SlicingDevice> getReference() {
        return doGetReference();
    }

    public static Reference<SlicingDevice> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private SlicingDevice() {
        this(null);
    }

    private SlicingDevice(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<SlicingDevice>{
        public Builder contribution(List<Reference<? extends SlicingDeviceContribution>> contribution) { SlicingDevice.this.contribution = contribution; return this; }
        public Builder description(String description) { SlicingDevice.this.description = description; return this; }
        public Builder internalIdentifier(String internalIdentifier) { SlicingDevice.this.internalIdentifier = internalIdentifier; return this; }
        public Builder name(String name) { SlicingDevice.this.name = name; return this; }
        public Builder serialNumber(String serialNumber) { SlicingDevice.this.serialNumber = serialNumber; return this; }
        public Builder type(Reference<? extends SlicingDeviceType> type) { SlicingDevice.this.type = type; return this; }
        

        public SlicingDevice build(OpenMINDSContext context) {
            SlicingDevice.super.build(context);
            return SlicingDevice.this;
        }
    }

    public static SlicingDevice.Builder create(LocalId localId){
        return new SlicingDevice(localId).new Builder();
    }

    public SlicingDevice.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, SlicingDevice.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/contribution")
    private List<Reference<? extends SlicingDeviceContribution>> contribution;
    
    public List<Reference<? extends SlicingDeviceContribution>> getContribution() {
       return this.contribution;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/internalIdentifier")
    private String internalIdentifier;
    
    /**
    * Term or code that identifies someone or something within a particular product.
    */
    public String getInternalIdentifier() {
       return this.internalIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/name")
    private String name;
    
    /**
    * Word or phrase that constitutes the distinctive designation of a being or thing.
    */
    public String getName() {
       return this.name;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/serialNumber")
    private String serialNumber;
    
    public String getSerialNumber() {
       return this.serialNumber;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/type")
    private Reference<? extends SlicingDeviceType> type;
    
    /**
    * Distinct class to which a group of entities or concepts with similar characteristics or attributes belong to.
    */
    public Reference<? extends SlicingDeviceType> getType() {
       return this.type;
    }

 

}