package org.openmetadatainitiative.openminds.latest.SANDS.atlas.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
public interface ParcellationEntityVersionRelationAssessment extends Entity {
   Reference<? extends ParcellationEntityVersionRelationAssessment> getReference();

   class Deserializer extends ByTypeDeserializer<ParcellationEntityVersionRelationAssessment> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.latest.SANDS.miscellaneous.QualitativeRelationAssessment.class, org.openmetadatainitiative.openminds.latest.SANDS.miscellaneous.QuantitativeRelationAssessment.class);
        }
    }
}