package org.openmetadatainitiative.openminds.v5.core.actors.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface OrganizationJurisdiction extends Entity {
   Reference<? extends OrganizationJurisdiction> getReference();

   class Deserializer extends ByTypeDeserializer<OrganizationJurisdiction> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.v5.controlledTerms.SovereignState.class, org.openmetadatainitiative.openminds.v5.controlledTerms.SupranationalBody.class);
        }
    }
    
}