package org.openmetadatainitiative.openminds.v4.SANDS.atlas.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface BrainAtlasVersionUsedSpecimen extends Entity {
   Reference<? extends BrainAtlasVersionUsedSpecimen> getReference();

   class Deserializer extends ByTypeDeserializer<BrainAtlasVersionUsedSpecimen> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.v4.core.research.Subject.class, org.openmetadatainitiative.openminds.v4.core.research.SubjectGroup.class, org.openmetadatainitiative.openminds.v4.core.research.TissueSample.class, org.openmetadatainitiative.openminds.v4.core.research.TissueSampleCollection.class);
        }
    }
    
}