package org.openmetadatainitiative.openminds.v5.ephys.device.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface ElectrodeArrayType extends Entity {
   Reference<? extends ElectrodeArrayType> getReference();

   class Deserializer extends ByTypeDeserializer<ElectrodeArrayType> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.v5.controlledTerms.DeviceType.class, org.openmetadatainitiative.openminds.v5.core.products.HardwareProduct.class);
        }
    }
    
}