package org.openmetadatainitiative.openminds.v5.neuroimaging.activity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.v5.chemicals.AmountOfChemical;
import org.openmetadatainitiative.openminds.v5.controlledTerms.AnatomicalAxesOrientation;
import org.openmetadatainitiative.openminds.v5.controlledTerms.PreparationType;
import org.openmetadatainitiative.openminds.v5.core.data.File;
import org.openmetadatainitiative.openminds.v5.core.miscellaneous.QuantitativeValue;
import org.openmetadatainitiative.openminds.v5.core.miscellaneous.QuantitativeValueArray;
import org.openmetadatainitiative.openminds.v5.core.products.DatasetVersion;
import org.openmetadatainitiative.openminds.v5.core.research.BehavioralProtocol;
import org.openmetadatainitiative.openminds.v5.core.research.CustomPropertySet;
import org.openmetadatainitiative.openminds.v5.core.research.Protocol;
import org.openmetadatainitiative.openminds.v5.neuroimaging.activity.intf.DynamicMRIAcquisitionInput;
import org.openmetadatainitiative.openminds.v5.neuroimaging.activity.intf.DynamicMRIAcquisitionPerformedBy;
import org.openmetadatainitiative.openminds.v5.neuroimaging.activity.intf.DynamicMRIAcquisitionStudyTarget;
import org.openmetadatainitiative.openminds.v5.neuroimaging.activity.intf.DynamicMRIAcquisitionTargetAnatomy;
import org.openmetadatainitiative.openminds.v5.neuroimaging.device.MRIScannerUsage;


import static org.openmetadatainitiative.openminds.v5.neuroimaging.activity.DynamicMRIAcquisition.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class DynamicMRIAcquisition extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.V5.Entity{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/DynamicMRIAcquisition";

    @JsonIgnore
    public Reference<DynamicMRIAcquisition> getReference() {
        return doGetReference();
    }

    public static Reference<DynamicMRIAcquisition> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private DynamicMRIAcquisition() {
        this(null);
    }

    private DynamicMRIAcquisition(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<DynamicMRIAcquisition>{
        public Builder behavioralProtocol(List<Reference<BehavioralProtocol>> behavioralProtocol) { DynamicMRIAcquisition.this.behavioralProtocol = behavioralProtocol; return this; }
        public Builder contrastAgent(List<Function<AmountOfChemical.EmbeddedBuilder, AmountOfChemical>> contrastAgent) { DynamicMRIAcquisition.this.contrastAgent = contrastAgent.stream().map(b -> b.apply(AmountOfChemical.createEmbedded())).toList(); return this; }
        public Builder customPropertySet(List<Function<CustomPropertySet.EmbeddedBuilder, CustomPropertySet>> customPropertySet) { DynamicMRIAcquisition.this.customPropertySet = customPropertySet.stream().map(b -> b.apply(CustomPropertySet.createEmbedded())).toList(); return this; }
        public Builder delayTime(Function<QuantitativeValue.EmbeddedBuilder, QuantitativeValue> delayTime) { DynamicMRIAcquisition.this.delayTime = delayTime.apply(QuantitativeValue.createEmbedded()); return this; }
        public Builder description(String description) { DynamicMRIAcquisition.this.description = description; return this; }
        public Builder device(Reference<MRIScannerUsage> device) { DynamicMRIAcquisition.this.device = device; return this; }
        public Builder distortionCorrection(List<Reference<File>> distortionCorrection) { DynamicMRIAcquisition.this.distortionCorrection = distortionCorrection; return this; }
        public Builder endTime(String endTime) { DynamicMRIAcquisition.this.endTime = endTime; return this; }
        public Builder input(List<Reference<? extends DynamicMRIAcquisitionInput>> input) { DynamicMRIAcquisition.this.input = input; return this; }
        public Builder isPartOf(Reference<DatasetVersion> isPartOf) { DynamicMRIAcquisition.this.isPartOf = isPartOf; return this; }
        public Builder lookupLabel(String lookupLabel) { DynamicMRIAcquisition.this.lookupLabel = lookupLabel; return this; }
        public Builder motionCorrection(List<Reference<File>> motionCorrection) { DynamicMRIAcquisition.this.motionCorrection = motionCorrection; return this; }
        public Builder numberOfDiscardedVolumes(Object numberOfDiscardedVolumes) { DynamicMRIAcquisition.this.numberOfDiscardedVolumes = numberOfDiscardedVolumes; return this; }
        public Builder output(List<Reference<File>> output) { DynamicMRIAcquisition.this.output = output; return this; }
        public Builder performedBy(List<Reference<? extends DynamicMRIAcquisitionPerformedBy>> performedBy) { DynamicMRIAcquisition.this.performedBy = performedBy; return this; }
        public Builder preparationDesign(Reference<PreparationType> preparationDesign) { DynamicMRIAcquisition.this.preparationDesign = preparationDesign; return this; }
        public Builder protocol(List<Reference<Protocol>> protocol) { DynamicMRIAcquisition.this.protocol = protocol; return this; }
        public Builder registrationData(List<Reference<File>> registrationData) { DynamicMRIAcquisition.this.registrationData = registrationData; return this; }
        public Builder specimenOrientation(Reference<AnatomicalAxesOrientation> specimenOrientation) { DynamicMRIAcquisition.this.specimenOrientation = specimenOrientation; return this; }
        public Builder startTime(String startTime) { DynamicMRIAcquisition.this.startTime = startTime; return this; }
        public Builder studyTarget(List<Reference<? extends DynamicMRIAcquisitionStudyTarget>> studyTarget) { DynamicMRIAcquisition.this.studyTarget = studyTarget; return this; }
        public Builder targetAnatomy(Reference<? extends DynamicMRIAcquisitionTargetAnatomy> targetAnatomy) { DynamicMRIAcquisition.this.targetAnatomy = targetAnatomy; return this; }
        public Builder volumeAcquisitionTime(Function<QuantitativeValue.EmbeddedBuilder, QuantitativeValue> volumeAcquisitionTime) { DynamicMRIAcquisition.this.volumeAcquisitionTime = volumeAcquisitionTime.apply(QuantitativeValue.createEmbedded()); return this; }
        public Builder volumeTiming(Function<QuantitativeValueArray.EmbeddedBuilder, QuantitativeValueArray> volumeTiming) { DynamicMRIAcquisition.this.volumeTiming = volumeTiming.apply(QuantitativeValueArray.createEmbedded()); return this; }
        

        public DynamicMRIAcquisition build(OpenMINDSContext context) {
            DynamicMRIAcquisition.super.build(context);
            return DynamicMRIAcquisition.this;
        }
    }

    public static DynamicMRIAcquisition.Builder create(LocalId localId){
        return new DynamicMRIAcquisition(localId).new Builder();
    }

    public DynamicMRIAcquisition.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, DynamicMRIAcquisition.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/behavioralProtocol")
    private List<Reference<BehavioralProtocol>> behavioralProtocol;
    
    public List<Reference<BehavioralProtocol>> getBehavioralProtocol() {
       return this.behavioralProtocol;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contrastAgent")
    private List<AmountOfChemical> contrastAgent;
    
    public List<AmountOfChemical> getContrastAgent() {
       return this.contrastAgent;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/customPropertySet")
    private List<CustomPropertySet> customPropertySet;
    
    public List<CustomPropertySet> getCustomPropertySet() {
       return this.customPropertySet;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/delayTime")
    private QuantitativeValue delayTime;
    
    public QuantitativeValue getDelayTime() {
       return this.delayTime;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/device")
    private Reference<MRIScannerUsage> device;
    
    /**
    * Piece of equipment or mechanism (hardware) designed to serve a special purpose or perform a special function.
    */
    public Reference<MRIScannerUsage> getDevice() {
       return this.device;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/distortionCorrection")
    private List<Reference<File>> distortionCorrection;
    
    public List<Reference<File>> getDistortionCorrection() {
       return this.distortionCorrection;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/endTime")
    private String endTime;
    
    public String getEndTime() {
       return this.endTime;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/input")
    private List<Reference<? extends DynamicMRIAcquisitionInput>> input;
    
    /**
    * Something or someone that is put into or participates in a process or machine.
    */
    public List<Reference<? extends DynamicMRIAcquisitionInput>> getInput() {
       return this.input;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isPartOf")
    private Reference<DatasetVersion> isPartOf;
    
    /**
    * Reference to the ensemble of multiple things or beings.
    */
    public Reference<DatasetVersion> getIsPartOf() {
       return this.isPartOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/lookupLabel")
    private String lookupLabel;
    
    public String getLookupLabel() {
       return this.lookupLabel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/motionCorrection")
    private List<Reference<File>> motionCorrection;
    
    public List<Reference<File>> getMotionCorrection() {
       return this.motionCorrection;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/numberOfDiscardedVolumes")
    private Object numberOfDiscardedVolumes;
    
    public Object getNumberOfDiscardedVolumes() {
       return this.numberOfDiscardedVolumes;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/output")
    private List<Reference<File>> output;
    
    /**
    * Something or someone that comes out of, is delivered or produced by a process or machine.
    */
    public List<Reference<File>> getOutput() {
       return this.output;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/performedBy")
    private List<Reference<? extends DynamicMRIAcquisitionPerformedBy>> performedBy;
    
    public List<Reference<? extends DynamicMRIAcquisitionPerformedBy>> getPerformedBy() {
       return this.performedBy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/preparationDesign")
    private Reference<PreparationType> preparationDesign;
    
    public Reference<PreparationType> getPreparationDesign() {
       return this.preparationDesign;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/protocol")
    private List<Reference<Protocol>> protocol;
    
    /**
    * Plan that describes the process of a scientific or medical experiment, treatment, or procedure.
    */
    public List<Reference<Protocol>> getProtocol() {
       return this.protocol;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/registrationData")
    private List<Reference<File>> registrationData;
    
    public List<Reference<File>> getRegistrationData() {
       return this.registrationData;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/specimenOrientation")
    private Reference<AnatomicalAxesOrientation> specimenOrientation;
    
    public Reference<AnatomicalAxesOrientation> getSpecimenOrientation() {
       return this.specimenOrientation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/startTime")
    private String startTime;
    
    public String getStartTime() {
       return this.startTime;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/studyTarget")
    private List<Reference<? extends DynamicMRIAcquisitionStudyTarget>> studyTarget;
    
    /**
    * Structure or function that was targeted within a study.
    */
    public List<Reference<? extends DynamicMRIAcquisitionStudyTarget>> getStudyTarget() {
       return this.studyTarget;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/targetAnatomy")
    private Reference<? extends DynamicMRIAcquisitionTargetAnatomy> targetAnatomy;
    
    public Reference<? extends DynamicMRIAcquisitionTargetAnatomy> getTargetAnatomy() {
       return this.targetAnatomy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/volumeAcquisitionTime")
    private QuantitativeValue volumeAcquisitionTime;
    
    public QuantitativeValue getVolumeAcquisitionTime() {
       return this.volumeAcquisitionTime;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/volumeTiming")
    private QuantitativeValueArray volumeTiming;
    
    public QuantitativeValueArray getVolumeTiming() {
       return this.volumeTiming;
    }

 

}