package org.openmetadatainitiative.openminds.v4.core.products.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface DatasetVersionLicense extends Entity {
   Reference<? extends DatasetVersionLicense> getReference();

   class Deserializer extends ByTypeDeserializer<DatasetVersionLicense> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.v4.core.data.License.class, org.openmetadatainitiative.openminds.v4.core.miscellaneous.WebResource.class);
        }
    }
    
}