package org.openmetadatainitiative.openminds.latest.SANDS.miscellaneous.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
public interface AnatomicalTargetPositionAnatomicalTarget extends Entity {
   Reference<? extends AnatomicalTargetPositionAnatomicalTarget> getReference();

   class Deserializer extends ByTypeDeserializer<AnatomicalTargetPositionAnatomicalTarget> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.latest.controlledTerms.CellType.class, org.openmetadatainitiative.openminds.latest.controlledTerms.Organ.class, org.openmetadatainitiative.openminds.latest.controlledTerms.OrganismSubstance.class, org.openmetadatainitiative.openminds.latest.controlledTerms.SubcellularEntity.class, org.openmetadatainitiative.openminds.latest.controlledTerms.UBERONParcellation.class, org.openmetadatainitiative.openminds.latest.SANDS.nonatlas.CustomAnatomicalEntity.class, org.openmetadatainitiative.openminds.latest.SANDS.atlas.ParcellationEntity.class, org.openmetadatainitiative.openminds.latest.SANDS.atlas.ParcellationEntityVersion.class);
        }
    }
}