package org.openmetadatainitiative.openminds.latest.ephys.activity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.latest.SANDS.miscellaneous.AnatomicalTargetPosition;
import org.openmetadatainitiative.openminds.latest.controlledTerms.PreparationType;
import org.openmetadatainitiative.openminds.latest.core.products.DatasetVersion;
import org.openmetadatainitiative.openminds.latest.core.research.CustomPropertySet;
import org.openmetadatainitiative.openminds.latest.core.research.Protocol;
import org.openmetadatainitiative.openminds.latest.ephys.activity.intf.ElectrodePlacementDevice;
import org.openmetadatainitiative.openminds.latest.ephys.activity.intf.ElectrodePlacementInput;
import org.openmetadatainitiative.openminds.latest.ephys.activity.intf.ElectrodePlacementOutput;
import org.openmetadatainitiative.openminds.latest.ephys.activity.intf.ElectrodePlacementPerformedBy;
import org.openmetadatainitiative.openminds.latest.ephys.activity.intf.ElectrodePlacementStudyTarget;


import static org.openmetadatainitiative.openminds.latest.ephys.activity.ElectrodePlacement.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class ElectrodePlacement extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.Latest.Entity{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/ElectrodePlacement";

    @JsonIgnore
    public Reference<ElectrodePlacement> getReference() {
        return doGetReference();
    }

    public static Reference<ElectrodePlacement> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private ElectrodePlacement() {
        this(null);
    }

    private ElectrodePlacement(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<ElectrodePlacement>{
        public Builder customPropertySet(List<Function<CustomPropertySet.EmbeddedBuilder, CustomPropertySet>> customPropertySet) { ElectrodePlacement.this.customPropertySet = customPropertySet.stream().map(b -> b.apply(CustomPropertySet.createEmbedded())).toList(); return this; }
        public Builder description(String description) { ElectrodePlacement.this.description = description; return this; }
        public Builder device(List<Reference<? extends ElectrodePlacementDevice>> device) { ElectrodePlacement.this.device = device; return this; }
        public Builder endTime(String endTime) { ElectrodePlacement.this.endTime = endTime; return this; }
        public Builder input(List<Reference<? extends ElectrodePlacementInput>> input) { ElectrodePlacement.this.input = input; return this; }
        public Builder isPartOf(Reference<DatasetVersion> isPartOf) { ElectrodePlacement.this.isPartOf = isPartOf; return this; }
        public Builder lookupLabel(String lookupLabel) { ElectrodePlacement.this.lookupLabel = lookupLabel; return this; }
        public Builder output(List<Reference<? extends ElectrodePlacementOutput>> output) { ElectrodePlacement.this.output = output; return this; }
        public Builder performedBy(List<Reference<? extends ElectrodePlacementPerformedBy>> performedBy) { ElectrodePlacement.this.performedBy = performedBy; return this; }
        public Builder preparationDesign(Reference<PreparationType> preparationDesign) { ElectrodePlacement.this.preparationDesign = preparationDesign; return this; }
        public Builder protocol(List<Reference<Protocol>> protocol) { ElectrodePlacement.this.protocol = protocol; return this; }
        public Builder startTime(String startTime) { ElectrodePlacement.this.startTime = startTime; return this; }
        public Builder studyTarget(List<Reference<? extends ElectrodePlacementStudyTarget>> studyTarget) { ElectrodePlacement.this.studyTarget = studyTarget; return this; }
        public Builder targetPosition(Function<AnatomicalTargetPosition.EmbeddedBuilder, AnatomicalTargetPosition> targetPosition) { ElectrodePlacement.this.targetPosition = targetPosition.apply(AnatomicalTargetPosition.createEmbedded()); return this; }
        

        public ElectrodePlacement build(OpenMINDSContext context) {
            ElectrodePlacement.super.build(context);
            return ElectrodePlacement.this;
        }
    }

    public static ElectrodePlacement.Builder create(LocalId localId){
        return new ElectrodePlacement(localId).new Builder();
    }

    public ElectrodePlacement.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, ElectrodePlacement.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/customPropertySet")
    private List<CustomPropertySet> customPropertySet;
    
    public List<CustomPropertySet> getCustomPropertySet() {
       return this.customPropertySet;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/device")
    private List<Reference<? extends ElectrodePlacementDevice>> device;
    
    /**
    * Piece of equipment or mechanism (hardware) designed to serve a special purpose or perform a special function.
    */
    public List<Reference<? extends ElectrodePlacementDevice>> getDevice() {
       return this.device;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/endTime")
    private String endTime;
    
    public String getEndTime() {
       return this.endTime;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/input")
    private List<Reference<? extends ElectrodePlacementInput>> input;
    
    /**
    * Something or someone that is put into or participates in a process or machine.
    */
    public List<Reference<? extends ElectrodePlacementInput>> getInput() {
       return this.input;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isPartOf")
    private Reference<DatasetVersion> isPartOf;
    
    /**
    * Reference to the ensemble of multiple things or beings.
    */
    public Reference<DatasetVersion> getIsPartOf() {
       return this.isPartOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/lookupLabel")
    private String lookupLabel;
    
    public String getLookupLabel() {
       return this.lookupLabel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/output")
    private List<Reference<? extends ElectrodePlacementOutput>> output;
    
    /**
    * Something or someone that comes out of, is delivered or produced by a process or machine.
    */
    public List<Reference<? extends ElectrodePlacementOutput>> getOutput() {
       return this.output;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/performedBy")
    private List<Reference<? extends ElectrodePlacementPerformedBy>> performedBy;
    
    public List<Reference<? extends ElectrodePlacementPerformedBy>> getPerformedBy() {
       return this.performedBy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/preparationDesign")
    private Reference<PreparationType> preparationDesign;
    
    public Reference<PreparationType> getPreparationDesign() {
       return this.preparationDesign;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/protocol")
    private List<Reference<Protocol>> protocol;
    
    /**
    * Plan that describes the process of a scientific or medical experiment, treatment, or procedure.
    */
    public List<Reference<Protocol>> getProtocol() {
       return this.protocol;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/startTime")
    private String startTime;
    
    public String getStartTime() {
       return this.startTime;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/studyTarget")
    private List<Reference<? extends ElectrodePlacementStudyTarget>> studyTarget;
    
    /**
    * Structure or function that was targeted within a study.
    */
    public List<Reference<? extends ElectrodePlacementStudyTarget>> getStudyTarget() {
       return this.studyTarget;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/targetPosition")
    private AnatomicalTargetPosition targetPosition;
    
    public AnatomicalTargetPosition getTargetPosition() {
       return this.targetPosition;
    }

 

}