package org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface RightConeBaseShape extends Entity {
   Reference<? extends RightConeBaseShape> getReference();

   class Deserializer extends ByTypeDeserializer<RightConeBaseShape> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.Circle.class, org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.Ellipse.class);
        }
    }
    
    static RightConeBaseShape.EmbeddedBuilder createEmbedded(){
        return new EmbeddedBuilder();
    }

    class EmbeddedBuilder {
        
        public org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.Circle.EmbeddedBuilder circle(){
            return org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.Circle.createEmbedded();
        }
        
        public org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.Ellipse.EmbeddedBuilder ellipse(){
            return org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.Ellipse.createEmbedded();
        }
        

    }
    
}