package org.openmetadatainitiative.openminds.latest.computation;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.latest.computation.ValidationTest;
import org.openmetadatainitiative.openminds.latest.computation.ValidationTestVersion;
import org.openmetadatainitiative.openminds.latest.computation.intf.ValidationTestVersionConfiguration;
import org.openmetadatainitiative.openminds.latest.computation.intf.ValidationTestVersionDocumentation;
import org.openmetadatainitiative.openminds.latest.computation.intf.ValidationTestVersionKeyword;
import org.openmetadatainitiative.openminds.latest.computation.intf.ValidationTestVersionReferenceData;
import org.openmetadatainitiative.openminds.latest.computation.intf.ValidationTestVersionRelatedPublication;
import org.openmetadatainitiative.openminds.latest.computation.intf.ValidationTestVersionUsageCondition;
import org.openmetadatainitiative.openminds.latest.controlledTerms.PublicationStatus;
import org.openmetadatainitiative.openminds.latest.core.actors.Affiliation;
import org.openmetadatainitiative.openminds.latest.core.actors.Contribution;
import org.openmetadatainitiative.openminds.latest.core.data.ContentType;
import org.openmetadatainitiative.openminds.latest.core.data.Copyright;
import org.openmetadatainitiative.openminds.latest.core.data.FileRepository;
import org.openmetadatainitiative.openminds.latest.core.digitalIdentifier.DOI;
import org.openmetadatainitiative.openminds.latest.core.miscellaneous.Accessibility;
import org.openmetadatainitiative.openminds.latest.core.miscellaneous.Funding;


import static org.openmetadatainitiative.openminds.latest.computation.ValidationTestVersion.SEMANTIC_NAME;
/**
 * Structured information about a specific implementation of a validation test.
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class ValidationTestVersion extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.Latest.Entity, org.openmetadatainitiative.openminds.latest.computation.intf.ModelValidationInput, org.openmetadatainitiative.openminds.latest.computation.intf.DataCopyInput, org.openmetadatainitiative.openminds.latest.publications.intf.LearningResourceAbout, org.openmetadatainitiative.openminds.latest.core.miscellaneous.intf.CommentAbout, org.openmetadatainitiative.openminds.latest.core.miscellaneous.intf.ResearchProductGroupHasPart, org.openmetadatainitiative.openminds.latest.core.products.intf.ProjectHasPart{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/ValidationTestVersion";

    @JsonIgnore
    public Reference<ValidationTestVersion> getReference() {
        return doGetReference();
    }

    public static Reference<ValidationTestVersion> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private ValidationTestVersion() {
        this(null);
    }

    private ValidationTestVersion(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<ValidationTestVersion>{
        public Builder accessibility(Reference<Accessibility> accessibility) { ValidationTestVersion.this.accessibility = accessibility; return this; }
        public Builder configuration(Reference<? extends ValidationTestVersionConfiguration> configuration) { ValidationTestVersion.this.configuration = configuration; return this; }
        public Builder contribution(List<Function<Contribution.EmbeddedBuilder, Contribution>> contribution) { ValidationTestVersion.this.contribution = contribution.stream().map(b -> b.apply(Contribution.createEmbedded())).toList(); return this; }
        public Builder contributorAffiliation(List<Function<Affiliation.EmbeddedBuilder, Affiliation>> contributorAffiliation) { ValidationTestVersion.this.contributorAffiliation = contributorAffiliation.stream().map(b -> b.apply(Affiliation.createEmbedded())).toList(); return this; }
        public Builder copyright(Function<Copyright.EmbeddedBuilder, Copyright> copyright) { ValidationTestVersion.this.copyright = copyright.apply(Copyright.createEmbedded()); return this; }
        public Builder description(String description) { ValidationTestVersion.this.description = description; return this; }
        public Builder digitalIdentifier(Reference<DOI> digitalIdentifier) { ValidationTestVersion.this.digitalIdentifier = digitalIdentifier; return this; }
        public Builder documentation(Reference<? extends ValidationTestVersionDocumentation> documentation) { ValidationTestVersion.this.documentation = documentation; return this; }
        public Builder entryPoint(String entryPoint) { ValidationTestVersion.this.entryPoint = entryPoint; return this; }
        public Builder format(Reference<ContentType> format) { ValidationTestVersion.this.format = format; return this; }
        public Builder fullName(String fullName) { ValidationTestVersion.this.fullName = fullName; return this; }
        public Builder funding(List<Reference<Funding>> funding) { ValidationTestVersion.this.funding = funding; return this; }
        public Builder homepage(String homepage) { ValidationTestVersion.this.homepage = homepage; return this; }
        public Builder howToCite(String howToCite) { ValidationTestVersion.this.howToCite = howToCite; return this; }
        public Builder isPrecededBy(Reference<ValidationTestVersion> isPrecededBy) { ValidationTestVersion.this.isPrecededBy = isPrecededBy; return this; }
        public Builder isVariantOf(List<Reference<ValidationTestVersion>> isVariantOf) { ValidationTestVersion.this.isVariantOf = isVariantOf; return this; }
        public Builder isVersionOf(Reference<ValidationTest> isVersionOf) { ValidationTestVersion.this.isVersionOf = isVersionOf; return this; }
        public Builder keyword(List<Reference<? extends ValidationTestVersionKeyword>> keyword) { ValidationTestVersion.this.keyword = keyword; return this; }
        public Builder publicationStatus(Reference<PublicationStatus> publicationStatus) { ValidationTestVersion.this.publicationStatus = publicationStatus; return this; }
        public Builder referenceData(List<Reference<? extends ValidationTestVersionReferenceData>> referenceData) { ValidationTestVersion.this.referenceData = referenceData; return this; }
        public Builder relatedPublication(List<Reference<? extends ValidationTestVersionRelatedPublication>> relatedPublication) { ValidationTestVersion.this.relatedPublication = relatedPublication; return this; }
        public Builder releaseDate(String releaseDate) { ValidationTestVersion.this.releaseDate = releaseDate; return this; }
        public Builder repository(Reference<FileRepository> repository) { ValidationTestVersion.this.repository = repository; return this; }
        public Builder shortName(String shortName) { ValidationTestVersion.this.shortName = shortName; return this; }
        public Builder supportChannel(List<String> supportChannel) { ValidationTestVersion.this.supportChannel = supportChannel; return this; }
        public Builder usageCondition(List<Reference<? extends ValidationTestVersionUsageCondition>> usageCondition) { ValidationTestVersion.this.usageCondition = usageCondition; return this; }
        public Builder versionIdentifier(String versionIdentifier) { ValidationTestVersion.this.versionIdentifier = versionIdentifier; return this; }
        public Builder versionSpecification(String versionSpecification) { ValidationTestVersion.this.versionSpecification = versionSpecification; return this; }
        

        public ValidationTestVersion build(OpenMINDSContext context) {
            ValidationTestVersion.super.build(context);
            return ValidationTestVersion.this;
        }
    }

    public static ValidationTestVersion.Builder create(LocalId localId){
        return new ValidationTestVersion(localId).new Builder();
    }

    public ValidationTestVersion.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, ValidationTestVersion.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/accessibility")
    private Reference<Accessibility> accessibility;
    
    /**
    * Level to which something is accessible to someone or something.
    */
    public Reference<Accessibility> getAccessibility() {
       return this.accessibility;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/configuration")
    private Reference<? extends ValidationTestVersionConfiguration> configuration;
    
    public Reference<? extends ValidationTestVersionConfiguration> getConfiguration() {
       return this.configuration;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contribution")
    private List<Contribution> contribution;
    
    public List<Contribution> getContribution() {
       return this.contribution;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contributorAffiliation")
    private List<Affiliation> contributorAffiliation;
    
    public List<Affiliation> getContributorAffiliation() {
       return this.contributorAffiliation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/copyright")
    private Copyright copyright;
    
    /**
    * Exclusive and assignable legal right of an originator to reproduce, publish, sell, or distribute the matter and form of a creative work for a defined time period.
    */
    public Copyright getCopyright() {
       return this.copyright;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/digitalIdentifier")
    private Reference<DOI> digitalIdentifier;
    
    /**
    * Digital handle to identify objects or legal persons.
    */
    public Reference<DOI> getDigitalIdentifier() {
       return this.digitalIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/documentation")
    private Reference<? extends ValidationTestVersionDocumentation> documentation;
    
    public Reference<? extends ValidationTestVersionDocumentation> getDocumentation() {
       return this.documentation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/entryPoint")
    private String entryPoint;
    
    public String getEntryPoint() {
       return this.entryPoint;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/format")
    private Reference<ContentType> format;
    
    /**
    * Method of digitally organizing and structuring data or information.
    */
    public Reference<ContentType> getFormat() {
       return this.format;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/fullName")
    private String fullName;
    
    /**
    * Whole, non-abbreviated name of something or somebody.
    */
    public String getFullName() {
       return this.fullName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/funding")
    private List<Reference<Funding>> funding;
    
    /**
    * Money provided by a legal person for a particular purpose.
    */
    public List<Reference<Funding>> getFunding() {
       return this.funding;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/homepage")
    private String homepage;
    
    /**
    * Main website of something or someone.
    */
    public String getHomepage() {
       return this.homepage;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/howToCite")
    private String howToCite;
    
    /**
    * Preferred format for citing a particular object or legal person.
    */
    public String getHowToCite() {
       return this.howToCite;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isPrecededBy")
    private Reference<ValidationTestVersion> isPrecededBy;
    
    public Reference<ValidationTestVersion> getIsPrecededBy() {
       return this.isPrecededBy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVariantOf")
    private List<Reference<ValidationTestVersion>> isVariantOf;
    
    public List<Reference<ValidationTestVersion>> getIsVariantOf() {
       return this.isVariantOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVersionOf")
    private Reference<ValidationTest> isVersionOf;
    
    public Reference<ValidationTest> getIsVersionOf() {
       return this.isVersionOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/keyword")
    private List<Reference<? extends ValidationTestVersionKeyword>> keyword;
    
    /**
    * Significant word or concept that are representative of something or someone.
    */
    public List<Reference<? extends ValidationTestVersionKeyword>> getKeyword() {
       return this.keyword;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/publicationStatus")
    private Reference<PublicationStatus> publicationStatus;
    
    public Reference<PublicationStatus> getPublicationStatus() {
       return this.publicationStatus;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/referenceData")
    private List<Reference<? extends ValidationTestVersionReferenceData>> referenceData;
    
    public List<Reference<? extends ValidationTestVersionReferenceData>> getReferenceData() {
       return this.referenceData;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/relatedPublication")
    private List<Reference<? extends ValidationTestVersionRelatedPublication>> relatedPublication;
    
    /**
    * Reference to something that was made available for the general public to see or buy.
    */
    public List<Reference<? extends ValidationTestVersionRelatedPublication>> getRelatedPublication() {
       return this.relatedPublication;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/releaseDate")
    private String releaseDate;
    
    /**
    * Fixed date on which a product is due to become or was made available for the general public to see or buy
    */
    public String getReleaseDate() {
       return this.releaseDate;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/repository")
    private Reference<FileRepository> repository;
    
    /**
    * Place, room, or container where something is deposited or stored.
    */
    public Reference<FileRepository> getRepository() {
       return this.repository;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/shortName")
    private String shortName;
    
    /**
    * Shortened or fully abbreviated name of something or somebody.
    */
    public String getShortName() {
       return this.shortName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/supportChannel")
    private List<String> supportChannel;
    
    /**
    * Way of communication used to interact with users or customers.
    */
    public List<String> getSupportChannel() {
       return this.supportChannel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/usageCondition")
    private List<Reference<? extends ValidationTestVersionUsageCondition>> usageCondition;
    
    public List<Reference<? extends ValidationTestVersionUsageCondition>> getUsageCondition() {
       return this.usageCondition;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionIdentifier")
    private String versionIdentifier;
    
    /**
    * Term or code used to identify the version of something.
    */
    public String getVersionIdentifier() {
       return this.versionIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionSpecification")
    private String versionSpecification;
    
    public String getVersionSpecification() {
       return this.versionSpecification;
    }

 

}