package org.openmetadatainitiative.openminds.v3.SANDS.miscellaneous.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface ViewerSpecificationPreferredDisplayColor extends Entity {
   Reference<? extends ViewerSpecificationPreferredDisplayColor> getReference();

   class Deserializer extends ByTypeDeserializer<ViewerSpecificationPreferredDisplayColor> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.v3.controlledTerms.Colormap.class, org.openmetadatainitiative.openminds.v3.SANDS.miscellaneous.SingleColor.class);
        }
    }
    
}