package org.openmetadatainitiative.openminds.latest.core.products.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface ModelVersionUsageCondition extends Entity {
   Reference<? extends ModelVersionUsageCondition> getReference();

   class Deserializer extends ByTypeDeserializer<ModelVersionUsageCondition> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.latest.core.data.License.class, org.openmetadatainitiative.openminds.latest.core.data.UsageAgreement.class);
        }
    }
    
}