package org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShapes;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.latest.core.miscellaneous.QuantitativeValue;


import static org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShapes.Rectangle.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class Rectangle extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.Latest.Entity, org.openmetadatainitiative.openminds.latest.specimenPrep.activity.intf.CranialWindowPreparationDimension{
    public static final String SEMANTIC_NAME = "https://openminds.ebrains.eu/sands/Rectangle";

    @JsonIgnore
    public Reference<Rectangle> getReference() {
        return doGetReference();
    }

    public static Reference<Rectangle> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private Rectangle() {
        this(null);
    }

    private Rectangle(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    
    public class EmbeddedBuilder {

        public EmbeddedBuilder length(Function<QuantitativeValue.EmbeddedBuilder, QuantitativeValue> length) { Rectangle.this.length = length.apply(QuantitativeValue.createEmbedded()); return this; }
        public EmbeddedBuilder width(Function<QuantitativeValue.EmbeddedBuilder, QuantitativeValue> width) { Rectangle.this.width = width.apply(QuantitativeValue.createEmbedded()); return this; }
        

        public Rectangle build(){
            return Rectangle.this;
        }
    }

    public static Rectangle.EmbeddedBuilder createEmbedded(){
        return new Rectangle(null).new EmbeddedBuilder();
    }
    

    

   @JsonProperty(value = "https://openminds.ebrains.eu/vocab/length")
    private QuantitativeValue length;
    
    public QuantitativeValue getLength() {
       return this.length;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/width")
    private QuantitativeValue width;
    
    public QuantitativeValue getWidth() {
       return this.width;
    }

 

}