package org.openmetadatainitiative.openminds.latest.neuroimaging.activity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.latest.chemicals.AmountOfChemical;
import org.openmetadatainitiative.openminds.latest.controlledTerms.AnatomicalAxesOrientation;
import org.openmetadatainitiative.openminds.latest.controlledTerms.PreparationType;
import org.openmetadatainitiative.openminds.latest.core.data.File;
import org.openmetadatainitiative.openminds.latest.core.products.DatasetVersion;
import org.openmetadatainitiative.openminds.latest.core.research.CustomPropertySet;
import org.openmetadatainitiative.openminds.latest.core.research.Protocol;
import org.openmetadatainitiative.openminds.latest.neuroimaging.activity.intf.StaticMRIAcquisitionInput;
import org.openmetadatainitiative.openminds.latest.neuroimaging.activity.intf.StaticMRIAcquisitionPerformedBy;
import org.openmetadatainitiative.openminds.latest.neuroimaging.activity.intf.StaticMRIAcquisitionStudyTarget;
import org.openmetadatainitiative.openminds.latest.neuroimaging.activity.intf.StaticMRIAcquisitionTargetAnatomy;
import org.openmetadatainitiative.openminds.latest.neuroimaging.device.MRIScannerUsage;


import static org.openmetadatainitiative.openminds.latest.neuroimaging.activity.StaticMRIAcquisition.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class StaticMRIAcquisition extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.Latest.Entity{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/StaticMRIAcquisition";

    @JsonIgnore
    public Reference<StaticMRIAcquisition> getReference() {
        return doGetReference();
    }

    public static Reference<StaticMRIAcquisition> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private StaticMRIAcquisition() {
        this(null);
    }

    private StaticMRIAcquisition(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<StaticMRIAcquisition>{
        public Builder contrastAgent(List<Function<AmountOfChemical.EmbeddedBuilder, AmountOfChemical>> contrastAgent) { StaticMRIAcquisition.this.contrastAgent = contrastAgent.stream().map(b -> b.apply(AmountOfChemical.createEmbedded())).toList(); return this; }
        public Builder customPropertySet(List<Function<CustomPropertySet.EmbeddedBuilder, CustomPropertySet>> customPropertySet) { StaticMRIAcquisition.this.customPropertySet = customPropertySet.stream().map(b -> b.apply(CustomPropertySet.createEmbedded())).toList(); return this; }
        public Builder description(String description) { StaticMRIAcquisition.this.description = description; return this; }
        public Builder device(Reference<MRIScannerUsage> device) { StaticMRIAcquisition.this.device = device; return this; }
        public Builder distortionCorrection(List<Reference<File>> distortionCorrection) { StaticMRIAcquisition.this.distortionCorrection = distortionCorrection; return this; }
        public Builder endTime(String endTime) { StaticMRIAcquisition.this.endTime = endTime; return this; }
        public Builder input(List<Reference<? extends StaticMRIAcquisitionInput>> input) { StaticMRIAcquisition.this.input = input; return this; }
        public Builder isPartOf(Reference<DatasetVersion> isPartOf) { StaticMRIAcquisition.this.isPartOf = isPartOf; return this; }
        public Builder lookupLabel(String lookupLabel) { StaticMRIAcquisition.this.lookupLabel = lookupLabel; return this; }
        public Builder motionCorrection(List<Reference<File>> motionCorrection) { StaticMRIAcquisition.this.motionCorrection = motionCorrection; return this; }
        public Builder output(List<Reference<File>> output) { StaticMRIAcquisition.this.output = output; return this; }
        public Builder performedBy(List<Reference<? extends StaticMRIAcquisitionPerformedBy>> performedBy) { StaticMRIAcquisition.this.performedBy = performedBy; return this; }
        public Builder preparationDesign(Reference<PreparationType> preparationDesign) { StaticMRIAcquisition.this.preparationDesign = preparationDesign; return this; }
        public Builder protocol(List<Reference<Protocol>> protocol) { StaticMRIAcquisition.this.protocol = protocol; return this; }
        public Builder registrationData(List<Reference<File>> registrationData) { StaticMRIAcquisition.this.registrationData = registrationData; return this; }
        public Builder specimenOrientation(Reference<AnatomicalAxesOrientation> specimenOrientation) { StaticMRIAcquisition.this.specimenOrientation = specimenOrientation; return this; }
        public Builder startTime(String startTime) { StaticMRIAcquisition.this.startTime = startTime; return this; }
        public Builder studyTarget(List<Reference<? extends StaticMRIAcquisitionStudyTarget>> studyTarget) { StaticMRIAcquisition.this.studyTarget = studyTarget; return this; }
        public Builder targetAnatomy(Reference<? extends StaticMRIAcquisitionTargetAnatomy> targetAnatomy) { StaticMRIAcquisition.this.targetAnatomy = targetAnatomy; return this; }
        

        public StaticMRIAcquisition build(OpenMINDSContext context) {
            StaticMRIAcquisition.super.build(context);
            return StaticMRIAcquisition.this;
        }
    }

    public static StaticMRIAcquisition.Builder create(LocalId localId){
        return new StaticMRIAcquisition(localId).new Builder();
    }

    public StaticMRIAcquisition.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, StaticMRIAcquisition.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/contrastAgent")
    private List<AmountOfChemical> contrastAgent;
    
    public List<AmountOfChemical> getContrastAgent() {
       return this.contrastAgent;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/customPropertySet")
    private List<CustomPropertySet> customPropertySet;
    
    public List<CustomPropertySet> getCustomPropertySet() {
       return this.customPropertySet;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/device")
    private Reference<MRIScannerUsage> device;
    
    /**
    * Piece of equipment or mechanism (hardware) designed to serve a special purpose or perform a special function.
    */
    public Reference<MRIScannerUsage> getDevice() {
       return this.device;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/distortionCorrection")
    private List<Reference<File>> distortionCorrection;
    
    public List<Reference<File>> getDistortionCorrection() {
       return this.distortionCorrection;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/endTime")
    private String endTime;
    
    public String getEndTime() {
       return this.endTime;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/input")
    private List<Reference<? extends StaticMRIAcquisitionInput>> input;
    
    /**
    * Something or someone that is put into or participates in a process or machine.
    */
    public List<Reference<? extends StaticMRIAcquisitionInput>> getInput() {
       return this.input;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isPartOf")
    private Reference<DatasetVersion> isPartOf;
    
    /**
    * Reference to the ensemble of multiple things or beings.
    */
    public Reference<DatasetVersion> getIsPartOf() {
       return this.isPartOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/lookupLabel")
    private String lookupLabel;
    
    public String getLookupLabel() {
       return this.lookupLabel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/motionCorrection")
    private List<Reference<File>> motionCorrection;
    
    public List<Reference<File>> getMotionCorrection() {
       return this.motionCorrection;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/output")
    private List<Reference<File>> output;
    
    /**
    * Something or someone that comes out of, is delivered or produced by a process or machine.
    */
    public List<Reference<File>> getOutput() {
       return this.output;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/performedBy")
    private List<Reference<? extends StaticMRIAcquisitionPerformedBy>> performedBy;
    
    public List<Reference<? extends StaticMRIAcquisitionPerformedBy>> getPerformedBy() {
       return this.performedBy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/preparationDesign")
    private Reference<PreparationType> preparationDesign;
    
    public Reference<PreparationType> getPreparationDesign() {
       return this.preparationDesign;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/protocol")
    private List<Reference<Protocol>> protocol;
    
    /**
    * Plan that describes the process of a scientific or medical experiment, treatment, or procedure.
    */
    public List<Reference<Protocol>> getProtocol() {
       return this.protocol;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/registrationData")
    private List<Reference<File>> registrationData;
    
    public List<Reference<File>> getRegistrationData() {
       return this.registrationData;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/specimenOrientation")
    private Reference<AnatomicalAxesOrientation> specimenOrientation;
    
    public Reference<AnatomicalAxesOrientation> getSpecimenOrientation() {
       return this.specimenOrientation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/startTime")
    private String startTime;
    
    public String getStartTime() {
       return this.startTime;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/studyTarget")
    private List<Reference<? extends StaticMRIAcquisitionStudyTarget>> studyTarget;
    
    /**
    * Structure or function that was targeted within a study.
    */
    public List<Reference<? extends StaticMRIAcquisitionStudyTarget>> getStudyTarget() {
       return this.studyTarget;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/targetAnatomy")
    private Reference<? extends StaticMRIAcquisitionTargetAnatomy> targetAnatomy;
    
    public Reference<? extends StaticMRIAcquisitionTargetAnatomy> getTargetAnatomy() {
       return this.targetAnatomy;
    }

 

}