package org.openmetadatainitiative.openminds.v5.SANDS.atlas;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.v5.SANDS.atlas.intf.CommonCoordinateFrameworkDigitalIdentifier;
import org.openmetadatainitiative.openminds.v5.SANDS.atlas.intf.CommonCoordinateFrameworkDocumentation;
import org.openmetadatainitiative.openminds.v5.SANDS.atlas.intf.CommonCoordinateFrameworkKeyword;
import org.openmetadatainitiative.openminds.v5.SANDS.atlas.intf.CommonCoordinateFrameworkRelatedPublication;
import org.openmetadatainitiative.openminds.v5.SANDS.atlas.intf.CommonCoordinateFrameworkUsedTaxon;
import org.openmetadatainitiative.openminds.v5.core.actors.Affiliation;
import org.openmetadatainitiative.openminds.v5.core.actors.Contribution;


import static org.openmetadatainitiative.openminds.v5.SANDS.atlas.CommonCoordinateFramework.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class CommonCoordinateFramework extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.V5.Entity, org.openmetadatainitiative.openminds.v5.core.products.intf.DatasetVersionInputData, org.openmetadatainitiative.openminds.v5.core.products.intf.ProjectHasPart, org.openmetadatainitiative.openminds.v5.core.data.intf.FileBundleGroupedBy, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.ResearchProductGroupHasPart, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.CommentAbout, org.openmetadatainitiative.openminds.v5.publications.intf.LearningResourceAbout{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/CommonCoordinateFramework";

    @JsonIgnore
    public Reference<CommonCoordinateFramework> getReference() {
        return doGetReference();
    }

    public static Reference<CommonCoordinateFramework> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private CommonCoordinateFramework() {
        this(null);
    }

    private CommonCoordinateFramework(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<CommonCoordinateFramework>{
        public Builder abbreviation(String abbreviation) { CommonCoordinateFramework.this.abbreviation = abbreviation; return this; }
        public Builder contribution(List<Function<Contribution.EmbeddedBuilder, Contribution>> contribution) { CommonCoordinateFramework.this.contribution = contribution.stream().map(b -> b.apply(Contribution.createEmbedded())).toList(); return this; }
        public Builder contributorAffiliation(List<Function<Affiliation.EmbeddedBuilder, Affiliation>> contributorAffiliation) { CommonCoordinateFramework.this.contributorAffiliation = contributorAffiliation.stream().map(b -> b.apply(Affiliation.createEmbedded())).toList(); return this; }
        public Builder description(String description) { CommonCoordinateFramework.this.description = description; return this; }
        public Builder digitalIdentifier(Reference<? extends CommonCoordinateFrameworkDigitalIdentifier> digitalIdentifier) { CommonCoordinateFramework.this.digitalIdentifier = digitalIdentifier; return this; }
        public Builder documentation(Reference<? extends CommonCoordinateFrameworkDocumentation> documentation) { CommonCoordinateFramework.this.documentation = documentation; return this; }
        public Builder fullName(String fullName) { CommonCoordinateFramework.this.fullName = fullName; return this; }
        public Builder homepage(String homepage) { CommonCoordinateFramework.this.homepage = homepage; return this; }
        public Builder howToCite(String howToCite) { CommonCoordinateFramework.this.howToCite = howToCite; return this; }
        public Builder keyword(List<Reference<? extends CommonCoordinateFrameworkKeyword>> keyword) { CommonCoordinateFramework.this.keyword = keyword; return this; }
        public Builder ontologyIdentifier(List<String> ontologyIdentifier) { CommonCoordinateFramework.this.ontologyIdentifier = ontologyIdentifier; return this; }
        public Builder relatedPublication(List<Reference<? extends CommonCoordinateFrameworkRelatedPublication>> relatedPublication) { CommonCoordinateFramework.this.relatedPublication = relatedPublication; return this; }
        public Builder shortName(String shortName) { CommonCoordinateFramework.this.shortName = shortName; return this; }
        public Builder supportChannel(List<String> supportChannel) { CommonCoordinateFramework.this.supportChannel = supportChannel; return this; }
        public Builder usedTaxon(Reference<? extends CommonCoordinateFrameworkUsedTaxon> usedTaxon) { CommonCoordinateFramework.this.usedTaxon = usedTaxon; return this; }
        

        public CommonCoordinateFramework build(OpenMINDSContext context) {
            CommonCoordinateFramework.super.build(context);
            return CommonCoordinateFramework.this;
        }
    }

    public static CommonCoordinateFramework.Builder create(LocalId localId){
        return new CommonCoordinateFramework(localId).new Builder();
    }

    public CommonCoordinateFramework.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, CommonCoordinateFramework.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/abbreviation")
    private String abbreviation;
    
    public String getAbbreviation() {
       return this.abbreviation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contribution")
    private List<Contribution> contribution;
    
    public List<Contribution> getContribution() {
       return this.contribution;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contributorAffiliation")
    private List<Affiliation> contributorAffiliation;
    
    public List<Affiliation> getContributorAffiliation() {
       return this.contributorAffiliation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/digitalIdentifier")
    private Reference<? extends CommonCoordinateFrameworkDigitalIdentifier> digitalIdentifier;
    
    /**
    * Digital handle to identify objects or legal persons.
    */
    public Reference<? extends CommonCoordinateFrameworkDigitalIdentifier> getDigitalIdentifier() {
       return this.digitalIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/documentation")
    private Reference<? extends CommonCoordinateFrameworkDocumentation> documentation;
    
    public Reference<? extends CommonCoordinateFrameworkDocumentation> getDocumentation() {
       return this.documentation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/fullName")
    private String fullName;
    
    /**
    * Whole, non-abbreviated name of something or somebody.
    */
    public String getFullName() {
       return this.fullName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/homepage")
    private String homepage;
    
    /**
    * Main website of something or someone.
    */
    public String getHomepage() {
       return this.homepage;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/howToCite")
    private String howToCite;
    
    /**
    * Preferred format for citing a particular object or legal person.
    */
    public String getHowToCite() {
       return this.howToCite;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/keyword")
    private List<Reference<? extends CommonCoordinateFrameworkKeyword>> keyword;
    
    /**
    * Significant word or concept that are representative of something or someone.
    */
    public List<Reference<? extends CommonCoordinateFrameworkKeyword>> getKeyword() {
       return this.keyword;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/ontologyIdentifier")
    private List<String> ontologyIdentifier;
    
    /**
    * Term or code used to identify something or someone registered within a particular ontology.
    */
    public List<String> getOntologyIdentifier() {
       return this.ontologyIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/relatedPublication")
    private List<Reference<? extends CommonCoordinateFrameworkRelatedPublication>> relatedPublication;
    
    /**
    * Reference to something that was made available for the general public to see or buy.
    */
    public List<Reference<? extends CommonCoordinateFrameworkRelatedPublication>> getRelatedPublication() {
       return this.relatedPublication;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/shortName")
    private String shortName;
    
    /**
    * Shortened or fully abbreviated name of something or somebody.
    */
    public String getShortName() {
       return this.shortName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/supportChannel")
    private List<String> supportChannel;
    
    /**
    * Way of communication used to interact with users or customers.
    */
    public List<String> getSupportChannel() {
       return this.supportChannel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/usedTaxon")
    private Reference<? extends CommonCoordinateFrameworkUsedTaxon> usedTaxon;
    
    public Reference<? extends CommonCoordinateFrameworkUsedTaxon> getUsedTaxon() {
       return this.usedTaxon;
    }

 

}