package org.openmetadatainitiative.openminds.latest.core.products;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.latest.controlledTerms.ExperimentalApproach;
import org.openmetadatainitiative.openminds.latest.controlledTerms.PreparationType;
import org.openmetadatainitiative.openminds.latest.controlledTerms.PublicationStatus;
import org.openmetadatainitiative.openminds.latest.controlledTerms.SemanticDataType;
import org.openmetadatainitiative.openminds.latest.core.actors.Affiliation;
import org.openmetadatainitiative.openminds.latest.core.actors.Contribution;
import org.openmetadatainitiative.openminds.latest.core.data.Copyright;
import org.openmetadatainitiative.openminds.latest.core.data.FileRepository;
import org.openmetadatainitiative.openminds.latest.core.miscellaneous.Accessibility;
import org.openmetadatainitiative.openminds.latest.core.miscellaneous.Funding;
import org.openmetadatainitiative.openminds.latest.core.products.Dataset;
import org.openmetadatainitiative.openminds.latest.core.products.DatasetVersion;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionDigitalIdentifier;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionDocumentation;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionEthicsJurisdiction;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionInputData;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionKeyword;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionProtocol;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionRelatedPublication;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionStudiedSpecimen;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionStudyTarget;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionTechnique;
import org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionUsageCondition;


import static org.openmetadatainitiative.openminds.latest.core.products.DatasetVersion.SEMANTIC_NAME;
/**
 * Structured information on data originating from human/animal studies or simulations (version level).
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class DatasetVersion extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.Latest.Entity, org.openmetadatainitiative.openminds.latest.computation.intf.DataCopyInput, org.openmetadatainitiative.openminds.latest.computation.intf.ServiceDeploymentDependsOn, org.openmetadatainitiative.openminds.latest.computation.intf.ServiceDeploymentUses, org.openmetadatainitiative.openminds.latest.publications.intf.LearningResourceAbout, org.openmetadatainitiative.openminds.latest.publications.intf.LivePaperVersionAbout, org.openmetadatainitiative.openminds.latest.core.miscellaneous.intf.CommentAbout, org.openmetadatainitiative.openminds.latest.core.miscellaneous.intf.ResearchProductGroupHasPart, org.openmetadatainitiative.openminds.latest.core.products.intf.ProjectHasPart{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/DatasetVersion";

    @JsonIgnore
    public Reference<DatasetVersion> getReference() {
        return doGetReference();
    }

    public static Reference<DatasetVersion> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private DatasetVersion() {
        this(null);
    }

    private DatasetVersion(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<DatasetVersion>{
        public Builder accessibility(Reference<Accessibility> accessibility) { DatasetVersion.this.accessibility = accessibility; return this; }
        public Builder contribution(List<Function<Contribution.EmbeddedBuilder, Contribution>> contribution) { DatasetVersion.this.contribution = contribution.stream().map(b -> b.apply(Contribution.createEmbedded())).toList(); return this; }
        public Builder contributorAffiliation(List<Function<Affiliation.EmbeddedBuilder, Affiliation>> contributorAffiliation) { DatasetVersion.this.contributorAffiliation = contributorAffiliation.stream().map(b -> b.apply(Affiliation.createEmbedded())).toList(); return this; }
        public Builder copyright(Function<Copyright.EmbeddedBuilder, Copyright> copyright) { DatasetVersion.this.copyright = copyright.apply(Copyright.createEmbedded()); return this; }
        public Builder dataType(List<Reference<SemanticDataType>> dataType) { DatasetVersion.this.dataType = dataType; return this; }
        public Builder description(String description) { DatasetVersion.this.description = description; return this; }
        public Builder digitalIdentifier(Reference<? extends DatasetVersionDigitalIdentifier> digitalIdentifier) { DatasetVersion.this.digitalIdentifier = digitalIdentifier; return this; }
        public Builder documentation(Reference<? extends DatasetVersionDocumentation> documentation) { DatasetVersion.this.documentation = documentation; return this; }
        public Builder ethicsJurisdiction(Reference<? extends DatasetVersionEthicsJurisdiction> ethicsJurisdiction) { DatasetVersion.this.ethicsJurisdiction = ethicsJurisdiction; return this; }
        public Builder experimentalApproach(List<Reference<ExperimentalApproach>> experimentalApproach) { DatasetVersion.this.experimentalApproach = experimentalApproach; return this; }
        public Builder fullName(String fullName) { DatasetVersion.this.fullName = fullName; return this; }
        public Builder funding(List<Reference<Funding>> funding) { DatasetVersion.this.funding = funding; return this; }
        public Builder homepage(String homepage) { DatasetVersion.this.homepage = homepage; return this; }
        public Builder howToCite(String howToCite) { DatasetVersion.this.howToCite = howToCite; return this; }
        public Builder inputData(List<Reference<? extends DatasetVersionInputData>> inputData) { DatasetVersion.this.inputData = inputData; return this; }
        public Builder isPrecededBy(Reference<DatasetVersion> isPrecededBy) { DatasetVersion.this.isPrecededBy = isPrecededBy; return this; }
        public Builder isVariantOf(List<Reference<DatasetVersion>> isVariantOf) { DatasetVersion.this.isVariantOf = isVariantOf; return this; }
        public Builder isVersionOf(Reference<Dataset> isVersionOf) { DatasetVersion.this.isVersionOf = isVersionOf; return this; }
        public Builder keyword(List<Reference<? extends DatasetVersionKeyword>> keyword) { DatasetVersion.this.keyword = keyword; return this; }
        public Builder preparationType(List<Reference<PreparationType>> preparationType) { DatasetVersion.this.preparationType = preparationType; return this; }
        public Builder protocol(List<Reference<? extends DatasetVersionProtocol>> protocol) { DatasetVersion.this.protocol = protocol; return this; }
        public Builder publicationStatus(Reference<PublicationStatus> publicationStatus) { DatasetVersion.this.publicationStatus = publicationStatus; return this; }
        public Builder relatedPublication(List<Reference<? extends DatasetVersionRelatedPublication>> relatedPublication) { DatasetVersion.this.relatedPublication = relatedPublication; return this; }
        public Builder releaseDate(String releaseDate) { DatasetVersion.this.releaseDate = releaseDate; return this; }
        public Builder repository(Reference<FileRepository> repository) { DatasetVersion.this.repository = repository; return this; }
        public Builder shortName(String shortName) { DatasetVersion.this.shortName = shortName; return this; }
        public Builder studiedSpecimen(List<Reference<? extends DatasetVersionStudiedSpecimen>> studiedSpecimen) { DatasetVersion.this.studiedSpecimen = studiedSpecimen; return this; }
        public Builder studyTarget(List<Reference<? extends DatasetVersionStudyTarget>> studyTarget) { DatasetVersion.this.studyTarget = studyTarget; return this; }
        public Builder supportChannel(List<String> supportChannel) { DatasetVersion.this.supportChannel = supportChannel; return this; }
        public Builder technique(List<Reference<? extends DatasetVersionTechnique>> technique) { DatasetVersion.this.technique = technique; return this; }
        public Builder usageCondition(List<Reference<? extends DatasetVersionUsageCondition>> usageCondition) { DatasetVersion.this.usageCondition = usageCondition; return this; }
        public Builder versionIdentifier(String versionIdentifier) { DatasetVersion.this.versionIdentifier = versionIdentifier; return this; }
        public Builder versionSpecification(String versionSpecification) { DatasetVersion.this.versionSpecification = versionSpecification; return this; }
        

        public DatasetVersion build(OpenMINDSContext context) {
            DatasetVersion.super.build(context);
            return DatasetVersion.this;
        }
    }

    public static DatasetVersion.Builder create(LocalId localId){
        return new DatasetVersion(localId).new Builder();
    }

    public DatasetVersion.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, DatasetVersion.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/accessibility")
    private Reference<Accessibility> accessibility;
    
    /**
    * Level to which something is accessible to someone or something.
    */
    public Reference<Accessibility> getAccessibility() {
       return this.accessibility;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contribution")
    private List<Contribution> contribution;
    
    public List<Contribution> getContribution() {
       return this.contribution;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contributorAffiliation")
    private List<Affiliation> contributorAffiliation;
    
    public List<Affiliation> getContributorAffiliation() {
       return this.contributorAffiliation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/copyright")
    private Copyright copyright;
    
    /**
    * Exclusive and assignable legal right of an originator to reproduce, publish, sell, or distribute the matter and form of a creative work for a defined time period.
    */
    public Copyright getCopyright() {
       return this.copyright;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/dataType")
    private List<Reference<SemanticDataType>> dataType;
    
    public List<Reference<SemanticDataType>> getDataType() {
       return this.dataType;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/digitalIdentifier")
    private Reference<? extends DatasetVersionDigitalIdentifier> digitalIdentifier;
    
    /**
    * Digital handle to identify objects or legal persons.
    */
    public Reference<? extends DatasetVersionDigitalIdentifier> getDigitalIdentifier() {
       return this.digitalIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/documentation")
    private Reference<? extends DatasetVersionDocumentation> documentation;
    
    public Reference<? extends DatasetVersionDocumentation> getDocumentation() {
       return this.documentation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/ethicsJurisdiction")
    private Reference<? extends DatasetVersionEthicsJurisdiction> ethicsJurisdiction;
    
    public Reference<? extends DatasetVersionEthicsJurisdiction> getEthicsJurisdiction() {
       return this.ethicsJurisdiction;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/experimentalApproach")
    private List<Reference<ExperimentalApproach>> experimentalApproach;
    
    public List<Reference<ExperimentalApproach>> getExperimentalApproach() {
       return this.experimentalApproach;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/fullName")
    private String fullName;
    
    /**
    * Whole, non-abbreviated name of something or somebody.
    */
    public String getFullName() {
       return this.fullName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/funding")
    private List<Reference<Funding>> funding;
    
    /**
    * Money provided by a legal person for a particular purpose.
    */
    public List<Reference<Funding>> getFunding() {
       return this.funding;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/homepage")
    private String homepage;
    
    /**
    * Main website of something or someone.
    */
    public String getHomepage() {
       return this.homepage;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/howToCite")
    private String howToCite;
    
    /**
    * Preferred format for citing a particular object or legal person.
    */
    public String getHowToCite() {
       return this.howToCite;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/inputData")
    private List<Reference<? extends DatasetVersionInputData>> inputData;
    
    /**
    * Data that is put into a process or machine.
    */
    public List<Reference<? extends DatasetVersionInputData>> getInputData() {
       return this.inputData;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isPrecededBy")
    private Reference<DatasetVersion> isPrecededBy;
    
    public Reference<DatasetVersion> getIsPrecededBy() {
       return this.isPrecededBy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVariantOf")
    private List<Reference<DatasetVersion>> isVariantOf;
    
    public List<Reference<DatasetVersion>> getIsVariantOf() {
       return this.isVariantOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVersionOf")
    private Reference<Dataset> isVersionOf;
    
    public Reference<Dataset> getIsVersionOf() {
       return this.isVersionOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/keyword")
    private List<Reference<? extends DatasetVersionKeyword>> keyword;
    
    /**
    * Significant word or concept that are representative of something or someone.
    */
    public List<Reference<? extends DatasetVersionKeyword>> getKeyword() {
       return this.keyword;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/preparationType")
    private List<Reference<PreparationType>> preparationType;
    
    /**
    * Distinct class of actions or processes that make something ready for use or service.
    */
    public List<Reference<PreparationType>> getPreparationType() {
       return this.preparationType;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/protocol")
    private List<Reference<? extends DatasetVersionProtocol>> protocol;
    
    /**
    * Plan that describes the process of a scientific or medical experiment, treatment, or procedure.
    */
    public List<Reference<? extends DatasetVersionProtocol>> getProtocol() {
       return this.protocol;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/publicationStatus")
    private Reference<PublicationStatus> publicationStatus;
    
    public Reference<PublicationStatus> getPublicationStatus() {
       return this.publicationStatus;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/relatedPublication")
    private List<Reference<? extends DatasetVersionRelatedPublication>> relatedPublication;
    
    /**
    * Reference to something that was made available for the general public to see or buy.
    */
    public List<Reference<? extends DatasetVersionRelatedPublication>> getRelatedPublication() {
       return this.relatedPublication;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/releaseDate")
    private String releaseDate;
    
    /**
    * Fixed date on which a product is due to become or was made available for the general public to see or buy
    */
    public String getReleaseDate() {
       return this.releaseDate;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/repository")
    private Reference<FileRepository> repository;
    
    /**
    * Place, room, or container where something is deposited or stored.
    */
    public Reference<FileRepository> getRepository() {
       return this.repository;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/shortName")
    private String shortName;
    
    /**
    * Shortened or fully abbreviated name of something or somebody.
    */
    public String getShortName() {
       return this.shortName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/studiedSpecimen")
    private List<Reference<? extends DatasetVersionStudiedSpecimen>> studiedSpecimen;
    
    public List<Reference<? extends DatasetVersionStudiedSpecimen>> getStudiedSpecimen() {
       return this.studiedSpecimen;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/studyTarget")
    private List<Reference<? extends DatasetVersionStudyTarget>> studyTarget;
    
    /**
    * Structure or function that was targeted within a study.
    */
    public List<Reference<? extends DatasetVersionStudyTarget>> getStudyTarget() {
       return this.studyTarget;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/supportChannel")
    private List<String> supportChannel;
    
    /**
    * Way of communication used to interact with users or customers.
    */
    public List<String> getSupportChannel() {
       return this.supportChannel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/technique")
    private List<Reference<? extends DatasetVersionTechnique>> technique;
    
    /**
    * Method of accomplishing a desired aim.
    */
    public List<Reference<? extends DatasetVersionTechnique>> getTechnique() {
       return this.technique;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/usageCondition")
    private List<Reference<? extends DatasetVersionUsageCondition>> usageCondition;
    
    public List<Reference<? extends DatasetVersionUsageCondition>> getUsageCondition() {
       return this.usageCondition;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionIdentifier")
    private String versionIdentifier;
    
    /**
    * Term or code used to identify the version of something.
    */
    public String getVersionIdentifier() {
       return this.versionIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionSpecification")
    private String versionSpecification;
    
    public String getVersionSpecification() {
       return this.versionSpecification;
    }

 

}