package org.openmetadatainitiative.openminds.v5.publications;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.v5.controlledTerms.PublicationStatus;
import org.openmetadatainitiative.openminds.v5.core.actors.Affiliation;
import org.openmetadatainitiative.openminds.v5.core.actors.Contribution;
import org.openmetadatainitiative.openminds.v5.core.data.Copyright;
import org.openmetadatainitiative.openminds.v5.core.data.FileRepository;
import org.openmetadatainitiative.openminds.v5.core.digitalIdentifier.DOI;
import org.openmetadatainitiative.openminds.v5.core.miscellaneous.Accessibility;
import org.openmetadatainitiative.openminds.v5.core.miscellaneous.Funding;
import org.openmetadatainitiative.openminds.v5.publications.LivePaper;
import org.openmetadatainitiative.openminds.v5.publications.LivePaperVersion;
import org.openmetadatainitiative.openminds.v5.publications.intf.LivePaperVersionAbout;
import org.openmetadatainitiative.openminds.v5.publications.intf.LivePaperVersionDocumentation;
import org.openmetadatainitiative.openminds.v5.publications.intf.LivePaperVersionKeyword;
import org.openmetadatainitiative.openminds.v5.publications.intf.LivePaperVersionRelatedPublication;
import org.openmetadatainitiative.openminds.v5.publications.intf.LivePaperVersionUsageCondition;


import static org.openmetadatainitiative.openminds.v5.publications.LivePaperVersion.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class LivePaperVersion extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.V5.Entity, org.openmetadatainitiative.openminds.v5.core.products.intf.ProjectHasPart, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.ResearchProductGroupHasPart, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.CommentAbout, org.openmetadatainitiative.openminds.v5.publications.intf.LearningResourceAbout{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/LivePaperVersion";

    @JsonIgnore
    public Reference<LivePaperVersion> getReference() {
        return doGetReference();
    }

    public static Reference<LivePaperVersion> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private LivePaperVersion() {
        this(null);
    }

    private LivePaperVersion(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<LivePaperVersion>{
        public Builder about(List<Reference<? extends LivePaperVersionAbout>> about) { LivePaperVersion.this.about = about; return this; }
        public Builder accessibility(Reference<Accessibility> accessibility) { LivePaperVersion.this.accessibility = accessibility; return this; }
        public Builder contribution(List<Function<Contribution.EmbeddedBuilder, Contribution>> contribution) { LivePaperVersion.this.contribution = contribution.stream().map(b -> b.apply(Contribution.createEmbedded())).toList(); return this; }
        public Builder contributorAffiliation(List<Function<Affiliation.EmbeddedBuilder, Affiliation>> contributorAffiliation) { LivePaperVersion.this.contributorAffiliation = contributorAffiliation.stream().map(b -> b.apply(Affiliation.createEmbedded())).toList(); return this; }
        public Builder copyright(Function<Copyright.EmbeddedBuilder, Copyright> copyright) { LivePaperVersion.this.copyright = copyright.apply(Copyright.createEmbedded()); return this; }
        public Builder description(String description) { LivePaperVersion.this.description = description; return this; }
        public Builder digitalIdentifier(Reference<DOI> digitalIdentifier) { LivePaperVersion.this.digitalIdentifier = digitalIdentifier; return this; }
        public Builder documentation(Reference<? extends LivePaperVersionDocumentation> documentation) { LivePaperVersion.this.documentation = documentation; return this; }
        public Builder fullName(String fullName) { LivePaperVersion.this.fullName = fullName; return this; }
        public Builder funding(List<Reference<Funding>> funding) { LivePaperVersion.this.funding = funding; return this; }
        public Builder homepage(String homepage) { LivePaperVersion.this.homepage = homepage; return this; }
        public Builder howToCite(String howToCite) { LivePaperVersion.this.howToCite = howToCite; return this; }
        public Builder isPrecededBy(Reference<LivePaperVersion> isPrecededBy) { LivePaperVersion.this.isPrecededBy = isPrecededBy; return this; }
        public Builder isVariantOf(List<Reference<LivePaperVersion>> isVariantOf) { LivePaperVersion.this.isVariantOf = isVariantOf; return this; }
        public Builder isVersionOf(Reference<LivePaper> isVersionOf) { LivePaperVersion.this.isVersionOf = isVersionOf; return this; }
        public Builder keyword(List<Reference<? extends LivePaperVersionKeyword>> keyword) { LivePaperVersion.this.keyword = keyword; return this; }
        public Builder modificationDate(String modificationDate) { LivePaperVersion.this.modificationDate = modificationDate; return this; }
        public Builder publicationStatus(Reference<PublicationStatus> publicationStatus) { LivePaperVersion.this.publicationStatus = publicationStatus; return this; }
        public Builder relatedPublication(List<Reference<? extends LivePaperVersionRelatedPublication>> relatedPublication) { LivePaperVersion.this.relatedPublication = relatedPublication; return this; }
        public Builder releaseDate(String releaseDate) { LivePaperVersion.this.releaseDate = releaseDate; return this; }
        public Builder repository(Reference<FileRepository> repository) { LivePaperVersion.this.repository = repository; return this; }
        public Builder shortName(String shortName) { LivePaperVersion.this.shortName = shortName; return this; }
        public Builder supportChannel(List<String> supportChannel) { LivePaperVersion.this.supportChannel = supportChannel; return this; }
        public Builder usageCondition(List<Reference<? extends LivePaperVersionUsageCondition>> usageCondition) { LivePaperVersion.this.usageCondition = usageCondition; return this; }
        public Builder versionIdentifier(String versionIdentifier) { LivePaperVersion.this.versionIdentifier = versionIdentifier; return this; }
        public Builder versionSpecification(String versionSpecification) { LivePaperVersion.this.versionSpecification = versionSpecification; return this; }
        

        public LivePaperVersion build(OpenMINDSContext context) {
            LivePaperVersion.super.build(context);
            return LivePaperVersion.this;
        }
    }

    public static LivePaperVersion.Builder create(LocalId localId){
        return new LivePaperVersion(localId).new Builder();
    }

    public LivePaperVersion.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, LivePaperVersion.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/about")
    private List<Reference<? extends LivePaperVersionAbout>> about;
    
    public List<Reference<? extends LivePaperVersionAbout>> getAbout() {
       return this.about;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/accessibility")
    private Reference<Accessibility> accessibility;
    
    /**
    * Level to which something is accessible to someone or something.
    */
    public Reference<Accessibility> getAccessibility() {
       return this.accessibility;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contribution")
    private List<Contribution> contribution;
    
    public List<Contribution> getContribution() {
       return this.contribution;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contributorAffiliation")
    private List<Affiliation> contributorAffiliation;
    
    public List<Affiliation> getContributorAffiliation() {
       return this.contributorAffiliation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/copyright")
    private Copyright copyright;
    
    /**
    * Exclusive and assignable legal right of an originator to reproduce, publish, sell, or distribute the matter and form of a creative work for a defined time period.
    */
    public Copyright getCopyright() {
       return this.copyright;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/digitalIdentifier")
    private Reference<DOI> digitalIdentifier;
    
    /**
    * Digital handle to identify objects or legal persons.
    */
    public Reference<DOI> getDigitalIdentifier() {
       return this.digitalIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/documentation")
    private Reference<? extends LivePaperVersionDocumentation> documentation;
    
    public Reference<? extends LivePaperVersionDocumentation> getDocumentation() {
       return this.documentation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/fullName")
    private String fullName;
    
    /**
    * Whole, non-abbreviated name of something or somebody.
    */
    public String getFullName() {
       return this.fullName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/funding")
    private List<Reference<Funding>> funding;
    
    /**
    * Money provided by a legal person for a particular purpose.
    */
    public List<Reference<Funding>> getFunding() {
       return this.funding;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/homepage")
    private String homepage;
    
    /**
    * Main website of something or someone.
    */
    public String getHomepage() {
       return this.homepage;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/howToCite")
    private String howToCite;
    
    /**
    * Preferred format for citing a particular object or legal person.
    */
    public String getHowToCite() {
       return this.howToCite;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isPrecededBy")
    private Reference<LivePaperVersion> isPrecededBy;
    
    public Reference<LivePaperVersion> getIsPrecededBy() {
       return this.isPrecededBy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVariantOf")
    private List<Reference<LivePaperVersion>> isVariantOf;
    
    public List<Reference<LivePaperVersion>> getIsVariantOf() {
       return this.isVariantOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVersionOf")
    private Reference<LivePaper> isVersionOf;
    
    public Reference<LivePaper> getIsVersionOf() {
       return this.isVersionOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/keyword")
    private List<Reference<? extends LivePaperVersionKeyword>> keyword;
    
    /**
    * Significant word or concept that are representative of something or someone.
    */
    public List<Reference<? extends LivePaperVersionKeyword>> getKeyword() {
       return this.keyword;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/modificationDate")
    private String modificationDate;
    
    public String getModificationDate() {
       return this.modificationDate;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/publicationStatus")
    private Reference<PublicationStatus> publicationStatus;
    
    public Reference<PublicationStatus> getPublicationStatus() {
       return this.publicationStatus;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/relatedPublication")
    private List<Reference<? extends LivePaperVersionRelatedPublication>> relatedPublication;
    
    /**
    * Reference to something that was made available for the general public to see or buy.
    */
    public List<Reference<? extends LivePaperVersionRelatedPublication>> getRelatedPublication() {
       return this.relatedPublication;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/releaseDate")
    private String releaseDate;
    
    /**
    * Fixed date on which a product is due to become or was made available for the general public to see or buy
    */
    public String getReleaseDate() {
       return this.releaseDate;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/repository")
    private Reference<FileRepository> repository;
    
    /**
    * Place, room, or container where something is deposited or stored.
    */
    public Reference<FileRepository> getRepository() {
       return this.repository;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/shortName")
    private String shortName;
    
    /**
    * Shortened or fully abbreviated name of something or somebody.
    */
    public String getShortName() {
       return this.shortName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/supportChannel")
    private List<String> supportChannel;
    
    /**
    * Way of communication used to interact with users or customers.
    */
    public List<String> getSupportChannel() {
       return this.supportChannel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/usageCondition")
    private List<Reference<? extends LivePaperVersionUsageCondition>> usageCondition;
    
    public List<Reference<? extends LivePaperVersionUsageCondition>> getUsageCondition() {
       return this.usageCondition;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionIdentifier")
    private String versionIdentifier;
    
    /**
    * Term or code used to identify the version of something.
    */
    public String getVersionIdentifier() {
       return this.versionIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionSpecification")
    private String versionSpecification;
    
    public String getVersionSpecification() {
       return this.versionSpecification;
    }

 

}