package org.openmetadatainitiative.openminds.v5.neuroimaging.device.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface MRICoilContribution extends Entity {
   Reference<? extends MRICoilContribution> getReference();

   class Deserializer extends ByTypeDeserializer<MRICoilContribution> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.v5.core.actors.Organization.class, org.openmetadatainitiative.openminds.v5.core.actors.Person.class);
        }
    }
    
}