package org.openmetadatainitiative.openminds.v3.computation;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.v3.computation.ValidationTestVersion;
import org.openmetadatainitiative.openminds.v3.computation.intf.ValidationTestVersionConfiguration;
import org.openmetadatainitiative.openminds.v3.computation.intf.ValidationTestVersionCustodian;
import org.openmetadatainitiative.openminds.v3.computation.intf.ValidationTestVersionDeveloper;
import org.openmetadatainitiative.openminds.v3.computation.intf.ValidationTestVersionFullDocumentation;
import org.openmetadatainitiative.openminds.v3.computation.intf.ValidationTestVersionKeyword;
import org.openmetadatainitiative.openminds.v3.computation.intf.ValidationTestVersionReferenceData;
import org.openmetadatainitiative.openminds.v3.computation.intf.ValidationTestVersionRelatedPublication;
import org.openmetadatainitiative.openminds.v3.controlledTerms.ProductAccessibility;
import org.openmetadatainitiative.openminds.v3.core.actors.Contribution;
import org.openmetadatainitiative.openminds.v3.core.data.ContentType;
import org.openmetadatainitiative.openminds.v3.core.data.Copyright;
import org.openmetadatainitiative.openminds.v3.core.data.FileRepository;
import org.openmetadatainitiative.openminds.v3.core.data.License;
import org.openmetadatainitiative.openminds.v3.core.digitalIdentifier.DOI;
import org.openmetadatainitiative.openminds.v3.core.miscellaneous.Funding;


import static org.openmetadatainitiative.openminds.v3.computation.ValidationTestVersion.SEMANTIC_NAME;
/**
 * Structured information about a specific implementation of a validation test.
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class ValidationTestVersion extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.V3.Entity, org.openmetadatainitiative.openminds.v3.publications.intf.LearningResourceAbout, org.openmetadatainitiative.openminds.v3.core.miscellaneous.intf.ResearchProductGroupHasPart, org.openmetadatainitiative.openminds.v3.core.miscellaneous.intf.CommentAbout, org.openmetadatainitiative.openminds.v3.core.products.intf.ProjectHasPart, org.openmetadatainitiative.openminds.v3.computation.intf.ModelValidationInput, org.openmetadatainitiative.openminds.v3.computation.intf.DataCopyInput{
    public static final String SEMANTIC_NAME = "https://openminds.ebrains.eu/computation/ValidationTestVersion";

    @JsonIgnore
    public Reference<ValidationTestVersion> getReference() {
        return doGetReference();
    }

    public static Reference<ValidationTestVersion> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private ValidationTestVersion() {
        this(null);
    }

    private ValidationTestVersion(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<ValidationTestVersion>{
        public Builder accessibility(Reference<ProductAccessibility> accessibility) { ValidationTestVersion.this.accessibility = accessibility; return this; }
        public Builder configuration(Reference<? extends ValidationTestVersionConfiguration> configuration) { ValidationTestVersion.this.configuration = configuration; return this; }
        public Builder copyright(Function<Copyright.EmbeddedBuilder, Copyright> copyright) { ValidationTestVersion.this.copyright = copyright.apply(Copyright.createEmbedded()); return this; }
        public Builder custodian(List<Reference<? extends ValidationTestVersionCustodian>> custodian) { ValidationTestVersion.this.custodian = custodian; return this; }
        public Builder description(String description) { ValidationTestVersion.this.description = description; return this; }
        public Builder developer(List<Reference<? extends ValidationTestVersionDeveloper>> developer) { ValidationTestVersion.this.developer = developer; return this; }
        public Builder digitalIdentifier(Reference<DOI> digitalIdentifier) { ValidationTestVersion.this.digitalIdentifier = digitalIdentifier; return this; }
        public Builder entryPoint(String entryPoint) { ValidationTestVersion.this.entryPoint = entryPoint; return this; }
        public Builder format(Reference<ContentType> format) { ValidationTestVersion.this.format = format; return this; }
        public Builder fullDocumentation(Reference<? extends ValidationTestVersionFullDocumentation> fullDocumentation) { ValidationTestVersion.this.fullDocumentation = fullDocumentation; return this; }
        public Builder fullName(String fullName) { ValidationTestVersion.this.fullName = fullName; return this; }
        public Builder funding(List<Reference<Funding>> funding) { ValidationTestVersion.this.funding = funding; return this; }
        public Builder homepage(String homepage) { ValidationTestVersion.this.homepage = homepage; return this; }
        public Builder howToCite(String howToCite) { ValidationTestVersion.this.howToCite = howToCite; return this; }
        public Builder isAlternativeVersionOf(List<Reference<ValidationTestVersion>> isAlternativeVersionOf) { ValidationTestVersion.this.isAlternativeVersionOf = isAlternativeVersionOf; return this; }
        public Builder isNewVersionOf(Reference<ValidationTestVersion> isNewVersionOf) { ValidationTestVersion.this.isNewVersionOf = isNewVersionOf; return this; }
        public Builder keyword(List<Reference<? extends ValidationTestVersionKeyword>> keyword) { ValidationTestVersion.this.keyword = keyword; return this; }
        public Builder license(List<Reference<License>> license) { ValidationTestVersion.this.license = license; return this; }
        public Builder otherContribution(List<Function<Contribution.EmbeddedBuilder, Contribution>> otherContribution) { ValidationTestVersion.this.otherContribution = otherContribution.stream().map(b -> b.apply(Contribution.createEmbedded())).toList(); return this; }
        public Builder referenceData(List<Reference<? extends ValidationTestVersionReferenceData>> referenceData) { ValidationTestVersion.this.referenceData = referenceData; return this; }
        public Builder relatedPublication(List<Reference<? extends ValidationTestVersionRelatedPublication>> relatedPublication) { ValidationTestVersion.this.relatedPublication = relatedPublication; return this; }
        public Builder releaseDate(String releaseDate) { ValidationTestVersion.this.releaseDate = releaseDate; return this; }
        public Builder repository(Reference<FileRepository> repository) { ValidationTestVersion.this.repository = repository; return this; }
        public Builder shortName(String shortName) { ValidationTestVersion.this.shortName = shortName; return this; }
        public Builder supportChannel(List<String> supportChannel) { ValidationTestVersion.this.supportChannel = supportChannel; return this; }
        public Builder versionIdentifier(String versionIdentifier) { ValidationTestVersion.this.versionIdentifier = versionIdentifier; return this; }
        public Builder versionInnovation(String versionInnovation) { ValidationTestVersion.this.versionInnovation = versionInnovation; return this; }
        

        public ValidationTestVersion build(OpenMINDSContext context) {
            ValidationTestVersion.super.build(context);
            return ValidationTestVersion.this;
        }
    }

    public static ValidationTestVersion.Builder create(LocalId localId){
        return new ValidationTestVersion(localId).new Builder();
    }

    public ValidationTestVersion.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, ValidationTestVersion.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.ebrains.eu/vocab/accessibility")
    private Reference<ProductAccessibility> accessibility;
    
    /**
    * Level to which something is accessible to someone or something.
    */
    public Reference<ProductAccessibility> getAccessibility() {
       return this.accessibility;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/configuration")
    private Reference<? extends ValidationTestVersionConfiguration> configuration;
    
    public Reference<? extends ValidationTestVersionConfiguration> getConfiguration() {
       return this.configuration;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/copyright")
    private Copyright copyright;
    
    /**
    * Exclusive and assignable legal right of an originator to reproduce, publish, sell, or distribute the matter and form of a creative work for a defined time period.
    */
    public Copyright getCopyright() {
       return this.copyright;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/custodian")
    private List<Reference<? extends ValidationTestVersionCustodian>> custodian;
    
    /**
    * The 'custodian' is a legal person who is responsible for the content and quality of the data, metadata, and/or code of a research product.
    */
    public List<Reference<? extends ValidationTestVersionCustodian>> getCustodian() {
       return this.custodian;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/developer")
    private List<Reference<? extends ValidationTestVersionDeveloper>> developer;
    
    /**
    * Legal person that creates or improves products or services (e.g., software, applications, etc.).
    */
    public List<Reference<? extends ValidationTestVersionDeveloper>> getDeveloper() {
       return this.developer;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/digitalIdentifier")
    private Reference<DOI> digitalIdentifier;
    
    /**
    * Digital handle to identify objects or legal persons.
    */
    public Reference<DOI> getDigitalIdentifier() {
       return this.digitalIdentifier;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/entryPoint")
    private String entryPoint;
    
    public String getEntryPoint() {
       return this.entryPoint;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/format")
    private Reference<ContentType> format;
    
    /**
    * Method of digitally organizing and structuring data or information.
    */
    public Reference<ContentType> getFormat() {
       return this.format;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/fullDocumentation")
    private Reference<? extends ValidationTestVersionFullDocumentation> fullDocumentation;
    
    /**
    * Non-abridged instructions, comments, and information for using a particular product.
    */
    public Reference<? extends ValidationTestVersionFullDocumentation> getFullDocumentation() {
       return this.fullDocumentation;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/fullName")
    private String fullName;
    
    /**
    * Whole, non-abbreviated name of something or somebody.
    */
    public String getFullName() {
       return this.fullName;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/funding")
    private List<Reference<Funding>> funding;
    
    /**
    * Money provided by a legal person for a particular purpose.
    */
    public List<Reference<Funding>> getFunding() {
       return this.funding;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/homepage")
    private String homepage;
    
    /**
    * Main website of something or someone.
    */
    public String getHomepage() {
       return this.homepage;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/howToCite")
    private String howToCite;
    
    /**
    * Preferred format for citing a particular object or legal person.
    */
    public String getHowToCite() {
       return this.howToCite;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/isAlternativeVersionOf")
    private List<Reference<ValidationTestVersion>> isAlternativeVersionOf;
    
    /**
    * Reference to an original form where the essence was preserved, but presented in an alternative form.
    */
    public List<Reference<ValidationTestVersion>> getIsAlternativeVersionOf() {
       return this.isAlternativeVersionOf;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/isNewVersionOf")
    private Reference<ValidationTestVersion> isNewVersionOf;
    
    /**
    * Reference to a previous (potentially outdated) particular form of something.
    */
    public Reference<ValidationTestVersion> getIsNewVersionOf() {
       return this.isNewVersionOf;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/keyword")
    private List<Reference<? extends ValidationTestVersionKeyword>> keyword;
    
    /**
    * Significant word or concept that are representative of something or someone.
    */
    public List<Reference<? extends ValidationTestVersionKeyword>> getKeyword() {
       return this.keyword;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/license")
    private List<Reference<License>> license;
    
    /**
    * Grant by a party to another party as an element of an agreement between those parties that permits to do, use, or own something.
    */
    public List<Reference<License>> getLicense() {
       return this.license;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/otherContribution")
    private List<Contribution> otherContribution;
    
    /**
    * Giving or supplying of something (such as money or time) as a part or share other than what is covered elsewhere.
    */
    public List<Contribution> getOtherContribution() {
       return this.otherContribution;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/referenceData")
    private List<Reference<? extends ValidationTestVersionReferenceData>> referenceData;
    
    public List<Reference<? extends ValidationTestVersionReferenceData>> getReferenceData() {
       return this.referenceData;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/relatedPublication")
    private List<Reference<? extends ValidationTestVersionRelatedPublication>> relatedPublication;
    
    /**
    * Reference to something that was made available for the general public to see or buy.
    */
    public List<Reference<? extends ValidationTestVersionRelatedPublication>> getRelatedPublication() {
       return this.relatedPublication;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/releaseDate")
    private String releaseDate;
    
    /**
    * Fixed date on which a product is due to become or was made available for the general public to see or buy
    */
    public String getReleaseDate() {
       return this.releaseDate;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/repository")
    private Reference<FileRepository> repository;
    
    /**
    * Place, room, or container where something is deposited or stored.
    */
    public Reference<FileRepository> getRepository() {
       return this.repository;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/shortName")
    private String shortName;
    
    /**
    * Shortened or fully abbreviated name of something or somebody.
    */
    public String getShortName() {
       return this.shortName;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/supportChannel")
    private List<String> supportChannel;
    
    /**
    * Way of communication used to interact with users or customers.
    */
    public List<String> getSupportChannel() {
       return this.supportChannel;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/versionIdentifier")
    private String versionIdentifier;
    
    /**
    * Term or code used to identify the version of something.
    */
    public String getVersionIdentifier() {
       return this.versionIdentifier;
    }

    @JsonProperty(value = "https://openminds.ebrains.eu/vocab/versionInnovation")
    private String versionInnovation;
    
    /**
    * Documentation on what changed in comparison to a previously published form of something.
    */
    public String getVersionInnovation() {
       return this.versionInnovation;
    }

 

}