package org.openmetadatainitiative.openminds.latest.core.digitalIdentifier;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.openmetadatainitiative.openminds.utils.*;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;



import static org.openmetadatainitiative.openminds.latest.core.digitalIdentifier.IdentifiersDotOrgID.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
public class IdentifiersDotOrgID extends Instance implements org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetDigitalIdentifier, org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionDigitalIdentifier{
    static final String SEMANTIC_NAME = "https://openminds.ebrains.eu/core/IdentifiersDotOrgID";

    @JsonIgnore
    public Reference<IdentifiersDotOrgID> getReference() {
        return doGetReference();
    }

    public static Reference<IdentifiersDotOrgID> createReference(InstanceId instanceId) {
        return new Reference<>(instanceId);
    }

    private IdentifiersDotOrgID(LocalId localId ) {
        super(localId);
    }


    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<IdentifiersDotOrgID>{
        
        public Builder identifier(String identifier) { IdentifiersDotOrgID.this.identifier = identifier; return this; }
        

        public IdentifiersDotOrgID build() {
            if (IdentifiersDotOrgID.this.id == null) {
                IdentifiersDotOrgID.this.id = new InstanceId(UUID.randomUUID().toString());
            }
            if(IdentifiersDotOrgID.this.types == null || IdentifiersDotOrgID.this.types.isEmpty() || !IdentifiersDotOrgID.this.types.contains(SEMANTIC_NAME)){
                final List<String> oldValues = IdentifiersDotOrgID.this.types;
                IdentifiersDotOrgID.this.types = new ArrayList<>();
                IdentifiersDotOrgID.this.types.add(SEMANTIC_NAME);
                if(oldValues != null){
                    IdentifiersDotOrgID.this.types.addAll(oldValues);
                }
            }
            return IdentifiersDotOrgID.this;
        }
    }

   @JsonProperty(value = "https://openminds.ebrains.eu/vocab/identifier")
    private String identifier;
    
    /**
    * Term or code used to identify something or someone.
    */
    public String getIdentifier() {
       return this.identifier;
    }

 
    public static IdentifiersDotOrgID.Builder create(LocalId localId){
        return new IdentifiersDotOrgID(localId).new Builder();
    }

    public IdentifiersDotOrgID.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, IdentifiersDotOrgID.class).new Builder();
    }
}