package org.openmetadatainitiative.openminds.latest.core.digitalIdentifier;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.openmetadatainitiative.openminds.utils.*;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;



import static org.openmetadatainitiative.openminds.latest.core.digitalIdentifier.ORCID.SEMANTIC_NAME;
/**
 * A persistent identifier for a researcher provided by Open Researcher and Contributor ID, Inc.
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ORCID extends Instance {
    static final String SEMANTIC_NAME = "https://openminds.ebrains.eu/core/ORCID";

    @JsonIgnore
    public Reference<ORCID> getReference() {
        return doGetReference();
    }

    public static Reference<ORCID> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    private ORCID(LocalId localId ) {
        super(localId);
    }


    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<ORCID>{
        
        public Builder identifier(String identifier) { ORCID.this.identifier = identifier; return this; }
        

        public ORCID build(OpenMINDSContext context) {
            if (ORCID.this.id == null) {
                ORCID.this.id = InstanceId.withPrefix(UUID.randomUUID().toString(), openMINDSContext.idPrefix());
            }
            ORCID.this.type = SEMANTIC_NAME;
            return ORCID.this;
        }
    }

   @JsonProperty(value = "https://openminds.ebrains.eu/vocab/identifier")
    private String identifier;
    
    /**
    * Term or code used to identify something or someone.
    */
    public String getIdentifier() {
       return this.identifier;
    }

 
    public static ORCID.Builder create(LocalId localId){
        return new ORCID(localId).new Builder();
    }

    public ORCID.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, ORCID.class).new Builder();
    }
}