package org.openmetadatainitiative.openminds.latest.SANDS.atlas;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.latest.SANDS.atlas.CommonCoordinateFramework;
import org.openmetadatainitiative.openminds.latest.SANDS.atlas.CommonCoordinateFrameworkVersion;
import org.openmetadatainitiative.openminds.latest.SANDS.atlas.intf.CommonCoordinateFrameworkVersionDigitalIdentifier;
import org.openmetadatainitiative.openminds.latest.SANDS.atlas.intf.CommonCoordinateFrameworkVersionDocumentation;
import org.openmetadatainitiative.openminds.latest.SANDS.atlas.intf.CommonCoordinateFrameworkVersionKeyword;
import org.openmetadatainitiative.openminds.latest.SANDS.atlas.intf.CommonCoordinateFrameworkVersionRelatedPublication;
import org.openmetadatainitiative.openminds.latest.SANDS.atlas.intf.CommonCoordinateFrameworkVersionUsageCondition;
import org.openmetadatainitiative.openminds.latest.SANDS.atlas.intf.CommonCoordinateFrameworkVersionUsedSpecimen;
import org.openmetadatainitiative.openminds.latest.controlledTerms.AnatomicalAxesOrientation;
import org.openmetadatainitiative.openminds.latest.controlledTerms.PublicationStatus;
import org.openmetadatainitiative.openminds.latest.controlledTerms.UnitOfMeasurement;
import org.openmetadatainitiative.openminds.latest.core.actors.Affiliation;
import org.openmetadatainitiative.openminds.latest.core.actors.Contribution;
import org.openmetadatainitiative.openminds.latest.core.data.Copyright;
import org.openmetadatainitiative.openminds.latest.core.data.File;
import org.openmetadatainitiative.openminds.latest.core.data.FileRepository;
import org.openmetadatainitiative.openminds.latest.core.miscellaneous.Accessibility;
import org.openmetadatainitiative.openminds.latest.core.miscellaneous.Funding;
import org.openmetadatainitiative.openminds.latest.core.miscellaneous.QuantitativeValue;


import static org.openmetadatainitiative.openminds.latest.SANDS.atlas.CommonCoordinateFrameworkVersion.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class CommonCoordinateFrameworkVersion extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.Latest.Entity, org.openmetadatainitiative.openminds.latest.computation.intf.ServiceDeploymentDependsOn, org.openmetadatainitiative.openminds.latest.computation.intf.ServiceDeploymentUses, org.openmetadatainitiative.openminds.latest.computation.intf.DataAnalysisInput, org.openmetadatainitiative.openminds.latest.core.products.intf.DatasetVersionInputData, org.openmetadatainitiative.openminds.latest.core.products.intf.ProjectHasPart, org.openmetadatainitiative.openminds.latest.core.research.intf.ProtocolExecutionInput, org.openmetadatainitiative.openminds.latest.core.data.intf.GridImageCoordinateFramework, org.openmetadatainitiative.openminds.latest.core.data.intf.GridVolumeSequenceCoordinateFramework, org.openmetadatainitiative.openminds.latest.core.data.intf.FileBundleGroupedBy, org.openmetadatainitiative.openminds.latest.core.data.intf.GridImageStackCoordinateFramework, org.openmetadatainitiative.openminds.latest.core.data.intf.GridVolumeCoordinateFramework, org.openmetadatainitiative.openminds.latest.core.miscellaneous.intf.ResearchProductGroupHasPart, org.openmetadatainitiative.openminds.latest.core.miscellaneous.intf.CommentAbout, org.openmetadatainitiative.openminds.latest.SANDS.nonatlas.intf.CustomAnnotationCoordinateFramework, org.openmetadatainitiative.openminds.latest.SANDS.miscellaneous.intf.CoordinatePointCoordinateFramework, org.openmetadatainitiative.openminds.latest.publications.intf.LearningResourceAbout{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/CommonCoordinateFrameworkVersion";

    @JsonIgnore
    public Reference<CommonCoordinateFrameworkVersion> getReference() {
        return doGetReference();
    }

    public static Reference<CommonCoordinateFrameworkVersion> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private CommonCoordinateFrameworkVersion() {
        this(null);
    }

    private CommonCoordinateFrameworkVersion(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<CommonCoordinateFrameworkVersion>{
        public Builder abbreviation(String abbreviation) { CommonCoordinateFrameworkVersion.this.abbreviation = abbreviation; return this; }
        public Builder accessibility(Reference<Accessibility> accessibility) { CommonCoordinateFrameworkVersion.this.accessibility = accessibility; return this; }
        public Builder anatomicalAxesOrientation(Reference<AnatomicalAxesOrientation> anatomicalAxesOrientation) { CommonCoordinateFrameworkVersion.this.anatomicalAxesOrientation = anatomicalAxesOrientation; return this; }
        public Builder axesOrigin(List<Function<QuantitativeValue.EmbeddedBuilder, QuantitativeValue>> axesOrigin) { CommonCoordinateFrameworkVersion.this.axesOrigin = axesOrigin.stream().map(b -> b.apply(QuantitativeValue.createEmbedded())).toList(); return this; }
        public Builder contribution(List<Function<Contribution.EmbeddedBuilder, Contribution>> contribution) { CommonCoordinateFrameworkVersion.this.contribution = contribution.stream().map(b -> b.apply(Contribution.createEmbedded())).toList(); return this; }
        public Builder contributorAffiliation(List<Function<Affiliation.EmbeddedBuilder, Affiliation>> contributorAffiliation) { CommonCoordinateFrameworkVersion.this.contributorAffiliation = contributorAffiliation.stream().map(b -> b.apply(Affiliation.createEmbedded())).toList(); return this; }
        public Builder copyright(Function<Copyright.EmbeddedBuilder, Copyright> copyright) { CommonCoordinateFrameworkVersion.this.copyright = copyright.apply(Copyright.createEmbedded()); return this; }
        public Builder defaultImage(List<Reference<File>> defaultImage) { CommonCoordinateFrameworkVersion.this.defaultImage = defaultImage; return this; }
        public Builder description(String description) { CommonCoordinateFrameworkVersion.this.description = description; return this; }
        public Builder digitalIdentifier(Reference<? extends CommonCoordinateFrameworkVersionDigitalIdentifier> digitalIdentifier) { CommonCoordinateFrameworkVersion.this.digitalIdentifier = digitalIdentifier; return this; }
        public Builder documentation(Reference<? extends CommonCoordinateFrameworkVersionDocumentation> documentation) { CommonCoordinateFrameworkVersion.this.documentation = documentation; return this; }
        public Builder fullName(String fullName) { CommonCoordinateFrameworkVersion.this.fullName = fullName; return this; }
        public Builder funding(List<Reference<Funding>> funding) { CommonCoordinateFrameworkVersion.this.funding = funding; return this; }
        public Builder homepage(String homepage) { CommonCoordinateFrameworkVersion.this.homepage = homepage; return this; }
        public Builder howToCite(String howToCite) { CommonCoordinateFrameworkVersion.this.howToCite = howToCite; return this; }
        public Builder isPrecededBy(Reference<CommonCoordinateFrameworkVersion> isPrecededBy) { CommonCoordinateFrameworkVersion.this.isPrecededBy = isPrecededBy; return this; }
        public Builder isVariantOf(List<Reference<CommonCoordinateFrameworkVersion>> isVariantOf) { CommonCoordinateFrameworkVersion.this.isVariantOf = isVariantOf; return this; }
        public Builder isVersionOf(Reference<CommonCoordinateFramework> isVersionOf) { CommonCoordinateFrameworkVersion.this.isVersionOf = isVersionOf; return this; }
        public Builder keyword(List<Reference<? extends CommonCoordinateFrameworkVersionKeyword>> keyword) { CommonCoordinateFrameworkVersion.this.keyword = keyword; return this; }
        public Builder nativeUnit(Reference<UnitOfMeasurement> nativeUnit) { CommonCoordinateFrameworkVersion.this.nativeUnit = nativeUnit; return this; }
        public Builder ontologyIdentifier(List<String> ontologyIdentifier) { CommonCoordinateFrameworkVersion.this.ontologyIdentifier = ontologyIdentifier; return this; }
        public Builder publicationStatus(Reference<PublicationStatus> publicationStatus) { CommonCoordinateFrameworkVersion.this.publicationStatus = publicationStatus; return this; }
        public Builder relatedPublication(List<Reference<? extends CommonCoordinateFrameworkVersionRelatedPublication>> relatedPublication) { CommonCoordinateFrameworkVersion.this.relatedPublication = relatedPublication; return this; }
        public Builder releaseDate(String releaseDate) { CommonCoordinateFrameworkVersion.this.releaseDate = releaseDate; return this; }
        public Builder repository(Reference<FileRepository> repository) { CommonCoordinateFrameworkVersion.this.repository = repository; return this; }
        public Builder shortName(String shortName) { CommonCoordinateFrameworkVersion.this.shortName = shortName; return this; }
        public Builder supportChannel(List<String> supportChannel) { CommonCoordinateFrameworkVersion.this.supportChannel = supportChannel; return this; }
        public Builder usageCondition(List<Reference<? extends CommonCoordinateFrameworkVersionUsageCondition>> usageCondition) { CommonCoordinateFrameworkVersion.this.usageCondition = usageCondition; return this; }
        public Builder usedSpecimen(List<Reference<? extends CommonCoordinateFrameworkVersionUsedSpecimen>> usedSpecimen) { CommonCoordinateFrameworkVersion.this.usedSpecimen = usedSpecimen; return this; }
        public Builder versionIdentifier(String versionIdentifier) { CommonCoordinateFrameworkVersion.this.versionIdentifier = versionIdentifier; return this; }
        public Builder versionSpecification(String versionSpecification) { CommonCoordinateFrameworkVersion.this.versionSpecification = versionSpecification; return this; }
        

        public CommonCoordinateFrameworkVersion build(OpenMINDSContext context) {
            CommonCoordinateFrameworkVersion.super.build(context);
            return CommonCoordinateFrameworkVersion.this;
        }
    }

    public static CommonCoordinateFrameworkVersion.Builder create(LocalId localId){
        return new CommonCoordinateFrameworkVersion(localId).new Builder();
    }

    public CommonCoordinateFrameworkVersion.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, CommonCoordinateFrameworkVersion.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/abbreviation")
    private String abbreviation;
    
    public String getAbbreviation() {
       return this.abbreviation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/accessibility")
    private Reference<Accessibility> accessibility;
    
    /**
    * Level to which something is accessible to someone or something.
    */
    public Reference<Accessibility> getAccessibility() {
       return this.accessibility;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/anatomicalAxesOrientation")
    private Reference<AnatomicalAxesOrientation> anatomicalAxesOrientation;
    
    /**
    * Relation between reference planes used in anatomy and mathematics.
    */
    public Reference<AnatomicalAxesOrientation> getAnatomicalAxesOrientation() {
       return this.anatomicalAxesOrientation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/axesOrigin")
    private List<QuantitativeValue> axesOrigin;
    
    /**
    * Special point in a coordinate system used as a fixed point of reference for the geometry of the surrounding space.
    */
    public List<QuantitativeValue> getAxesOrigin() {
       return this.axesOrigin;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contribution")
    private List<Contribution> contribution;
    
    public List<Contribution> getContribution() {
       return this.contribution;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contributorAffiliation")
    private List<Affiliation> contributorAffiliation;
    
    public List<Affiliation> getContributorAffiliation() {
       return this.contributorAffiliation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/copyright")
    private Copyright copyright;
    
    /**
    * Exclusive and assignable legal right of an originator to reproduce, publish, sell, or distribute the matter and form of a creative work for a defined time period.
    */
    public Copyright getCopyright() {
       return this.copyright;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/defaultImage")
    private List<Reference<File>> defaultImage;
    
    /**
    * Two or three dimensional image that particluarly represents a specific coordinate space.
    */
    public List<Reference<File>> getDefaultImage() {
       return this.defaultImage;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/digitalIdentifier")
    private Reference<? extends CommonCoordinateFrameworkVersionDigitalIdentifier> digitalIdentifier;
    
    /**
    * Digital handle to identify objects or legal persons.
    */
    public Reference<? extends CommonCoordinateFrameworkVersionDigitalIdentifier> getDigitalIdentifier() {
       return this.digitalIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/documentation")
    private Reference<? extends CommonCoordinateFrameworkVersionDocumentation> documentation;
    
    public Reference<? extends CommonCoordinateFrameworkVersionDocumentation> getDocumentation() {
       return this.documentation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/fullName")
    private String fullName;
    
    /**
    * Whole, non-abbreviated name of something or somebody.
    */
    public String getFullName() {
       return this.fullName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/funding")
    private List<Reference<Funding>> funding;
    
    /**
    * Money provided by a legal person for a particular purpose.
    */
    public List<Reference<Funding>> getFunding() {
       return this.funding;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/homepage")
    private String homepage;
    
    /**
    * Main website of something or someone.
    */
    public String getHomepage() {
       return this.homepage;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/howToCite")
    private String howToCite;
    
    /**
    * Preferred format for citing a particular object or legal person.
    */
    public String getHowToCite() {
       return this.howToCite;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isPrecededBy")
    private Reference<CommonCoordinateFrameworkVersion> isPrecededBy;
    
    public Reference<CommonCoordinateFrameworkVersion> getIsPrecededBy() {
       return this.isPrecededBy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVariantOf")
    private List<Reference<CommonCoordinateFrameworkVersion>> isVariantOf;
    
    public List<Reference<CommonCoordinateFrameworkVersion>> getIsVariantOf() {
       return this.isVariantOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVersionOf")
    private Reference<CommonCoordinateFramework> isVersionOf;
    
    public Reference<CommonCoordinateFramework> getIsVersionOf() {
       return this.isVersionOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/keyword")
    private List<Reference<? extends CommonCoordinateFrameworkVersionKeyword>> keyword;
    
    /**
    * Significant word or concept that are representative of something or someone.
    */
    public List<Reference<? extends CommonCoordinateFrameworkVersionKeyword>> getKeyword() {
       return this.keyword;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/nativeUnit")
    private Reference<UnitOfMeasurement> nativeUnit;
    
    /**
    * Determinate quantity used in the original measurement.
    */
    public Reference<UnitOfMeasurement> getNativeUnit() {
       return this.nativeUnit;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/ontologyIdentifier")
    private List<String> ontologyIdentifier;
    
    /**
    * Term or code used to identify something or someone registered within a particular ontology.
    */
    public List<String> getOntologyIdentifier() {
       return this.ontologyIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/publicationStatus")
    private Reference<PublicationStatus> publicationStatus;
    
    public Reference<PublicationStatus> getPublicationStatus() {
       return this.publicationStatus;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/relatedPublication")
    private List<Reference<? extends CommonCoordinateFrameworkVersionRelatedPublication>> relatedPublication;
    
    /**
    * Reference to something that was made available for the general public to see or buy.
    */
    public List<Reference<? extends CommonCoordinateFrameworkVersionRelatedPublication>> getRelatedPublication() {
       return this.relatedPublication;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/releaseDate")
    private String releaseDate;
    
    /**
    * Fixed date on which a product is due to become or was made available for the general public to see or buy
    */
    public String getReleaseDate() {
       return this.releaseDate;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/repository")
    private Reference<FileRepository> repository;
    
    /**
    * Place, room, or container where something is deposited or stored.
    */
    public Reference<FileRepository> getRepository() {
       return this.repository;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/shortName")
    private String shortName;
    
    /**
    * Shortened or fully abbreviated name of something or somebody.
    */
    public String getShortName() {
       return this.shortName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/supportChannel")
    private List<String> supportChannel;
    
    /**
    * Way of communication used to interact with users or customers.
    */
    public List<String> getSupportChannel() {
       return this.supportChannel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/usageCondition")
    private List<Reference<? extends CommonCoordinateFrameworkVersionUsageCondition>> usageCondition;
    
    public List<Reference<? extends CommonCoordinateFrameworkVersionUsageCondition>> getUsageCondition() {
       return this.usageCondition;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/usedSpecimen")
    private List<Reference<? extends CommonCoordinateFrameworkVersionUsedSpecimen>> usedSpecimen;
    
    public List<Reference<? extends CommonCoordinateFrameworkVersionUsedSpecimen>> getUsedSpecimen() {
       return this.usedSpecimen;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionIdentifier")
    private String versionIdentifier;
    
    /**
    * Term or code used to identify the version of something.
    */
    public String getVersionIdentifier() {
       return this.versionIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionSpecification")
    private String versionSpecification;
    
    public String getVersionSpecification() {
       return this.versionSpecification;
    }

 

}