package org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.latest.core.miscellaneous.QuantitativeValue;


import static org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.Cube.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class Cube extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.Latest.Entity, org.openmetadatainitiative.openminds.latest.specimenPrep.activity.intf.CranialWindowPreparationDimension{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/Cube";

    @JsonIgnore
    public Reference<Cube> getReference() {
        return doGetReference();
    }

    public static Reference<Cube> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private Cube() {
        this(null);
    }

    private Cube(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    
    public class EmbeddedBuilder {

        public EmbeddedBuilder sideLength(Function<QuantitativeValue.EmbeddedBuilder, QuantitativeValue> sideLength) { Cube.this.sideLength = sideLength.apply(QuantitativeValue.createEmbedded()); return this; }
        

        public Cube build(){
            return Cube.this;
        }
    }

    public static Cube.EmbeddedBuilder createEmbedded(){
        return new Cube(null).new EmbeddedBuilder();
    }
    

    

   @JsonProperty(value = "https://openminds.om-i.org/props/sideLength")
    private QuantitativeValue sideLength;
    
    public QuantitativeValue getSideLength() {
       return this.sideLength;
    }

 

}