package org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.latest.core.miscellaneous.QuantitativeValue;


import static org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.Trapezoid.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class Trapezoid extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.Latest.Entity, org.openmetadatainitiative.openminds.latest.specimenPrep.activity.intf.CranialWindowPreparationDimension, org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.intf.RightPrismBaseShape, org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.intf.CentroidalPyramidBaseShape, org.openmetadatainitiative.openminds.latest.SANDS.mathematicalShape.intf.FrustumMajorBaseShape{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/Trapezoid";

    @JsonIgnore
    public Reference<Trapezoid> getReference() {
        return doGetReference();
    }

    public static Reference<Trapezoid> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private Trapezoid() {
        this(null);
    }

    private Trapezoid(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    
    public class EmbeddedBuilder {

        public EmbeddedBuilder baseDistance(Function<QuantitativeValue.EmbeddedBuilder, QuantitativeValue> baseDistance) { Trapezoid.this.baseDistance = baseDistance.apply(QuantitativeValue.createEmbedded()); return this; }
        public EmbeddedBuilder baseLengths(List<Function<QuantitativeValue.EmbeddedBuilder, QuantitativeValue>> baseLengths) { Trapezoid.this.baseLengths = baseLengths.stream().map(b -> b.apply(QuantitativeValue.createEmbedded())).toList(); return this; }
        

        public Trapezoid build(){
            return Trapezoid.this;
        }
    }

    public static Trapezoid.EmbeddedBuilder createEmbedded(){
        return new Trapezoid(null).new EmbeddedBuilder();
    }
    

    

   @JsonProperty(value = "https://openminds.om-i.org/props/baseDistance")
    private QuantitativeValue baseDistance;
    
    public QuantitativeValue getBaseDistance() {
       return this.baseDistance;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/baseLengths")
    private List<QuantitativeValue> baseLengths;
    
    public List<QuantitativeValue> getBaseLengths() {
       return this.baseLengths;
    }

 

}