package org.openmetadatainitiative.openminds.v5.core.products;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.v5.controlledTerms.PublicationStatus;
import org.openmetadatainitiative.openminds.v5.core.actors.Affiliation;
import org.openmetadatainitiative.openminds.v5.core.actors.Contribution;
import org.openmetadatainitiative.openminds.v5.core.data.Copyright;
import org.openmetadatainitiative.openminds.v5.core.data.FileRepository;
import org.openmetadatainitiative.openminds.v5.core.miscellaneous.Accessibility;
import org.openmetadatainitiative.openminds.v5.core.miscellaneous.Funding;
import org.openmetadatainitiative.openminds.v5.core.products.Interface;
import org.openmetadatainitiative.openminds.v5.core.products.InterfaceVersion;
import org.openmetadatainitiative.openminds.v5.core.products.intf.InterfaceVersionDocumentation;
import org.openmetadatainitiative.openminds.v5.core.products.intf.InterfaceVersionKeyword;
import org.openmetadatainitiative.openminds.v5.core.products.intf.InterfaceVersionRelatedPublication;
import org.openmetadatainitiative.openminds.v5.core.products.intf.InterfaceVersionSpecification;
import org.openmetadatainitiative.openminds.v5.core.products.intf.InterfaceVersionUsageCondition;


import static org.openmetadatainitiative.openminds.v5.core.products.InterfaceVersion.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class InterfaceVersion extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.V5.Entity, org.openmetadatainitiative.openminds.v5.publications.intf.LearningResourceAbout, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.DependencyFulfilledBy, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.CommentAbout, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.ResearchProductGroupHasPart, org.openmetadatainitiative.openminds.v5.core.products.intf.ProjectHasPart, org.openmetadatainitiative.openminds.v5.core.data.intf.ServiceLinkService{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/InterfaceVersion";

    @JsonIgnore
    public Reference<InterfaceVersion> getReference() {
        return doGetReference();
    }

    public static Reference<InterfaceVersion> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private InterfaceVersion() {
        this(null);
    }

    private InterfaceVersion(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<InterfaceVersion>{
        public Builder accessibility(Reference<Accessibility> accessibility) { InterfaceVersion.this.accessibility = accessibility; return this; }
        public Builder contribution(List<Function<Contribution.EmbeddedBuilder, Contribution>> contribution) { InterfaceVersion.this.contribution = contribution.stream().map(b -> b.apply(Contribution.createEmbedded())).toList(); return this; }
        public Builder contributorAffiliation(List<Function<Affiliation.EmbeddedBuilder, Affiliation>> contributorAffiliation) { InterfaceVersion.this.contributorAffiliation = contributorAffiliation.stream().map(b -> b.apply(Affiliation.createEmbedded())).toList(); return this; }
        public Builder copyright(Function<Copyright.EmbeddedBuilder, Copyright> copyright) { InterfaceVersion.this.copyright = copyright.apply(Copyright.createEmbedded()); return this; }
        public Builder description(String description) { InterfaceVersion.this.description = description; return this; }
        public Builder documentation(Reference<? extends InterfaceVersionDocumentation> documentation) { InterfaceVersion.this.documentation = documentation; return this; }
        public Builder fullName(String fullName) { InterfaceVersion.this.fullName = fullName; return this; }
        public Builder funding(List<Reference<Funding>> funding) { InterfaceVersion.this.funding = funding; return this; }
        public Builder homepage(String homepage) { InterfaceVersion.this.homepage = homepage; return this; }
        public Builder howToCite(String howToCite) { InterfaceVersion.this.howToCite = howToCite; return this; }
        public Builder isPrecededBy(Reference<InterfaceVersion> isPrecededBy) { InterfaceVersion.this.isPrecededBy = isPrecededBy; return this; }
        public Builder isVariantOf(List<Reference<InterfaceVersion>> isVariantOf) { InterfaceVersion.this.isVariantOf = isVariantOf; return this; }
        public Builder isVersionOf(Reference<Interface> isVersionOf) { InterfaceVersion.this.isVersionOf = isVersionOf; return this; }
        public Builder keyword(List<Reference<? extends InterfaceVersionKeyword>> keyword) { InterfaceVersion.this.keyword = keyword; return this; }
        public Builder publicationStatus(Reference<PublicationStatus> publicationStatus) { InterfaceVersion.this.publicationStatus = publicationStatus; return this; }
        public Builder relatedPublication(List<Reference<? extends InterfaceVersionRelatedPublication>> relatedPublication) { InterfaceVersion.this.relatedPublication = relatedPublication; return this; }
        public Builder releaseDate(String releaseDate) { InterfaceVersion.this.releaseDate = releaseDate; return this; }
        public Builder repository(Reference<FileRepository> repository) { InterfaceVersion.this.repository = repository; return this; }
        public Builder shortName(String shortName) { InterfaceVersion.this.shortName = shortName; return this; }
        public Builder specification(Reference<? extends InterfaceVersionSpecification> specification) { InterfaceVersion.this.specification = specification; return this; }
        public Builder supportChannel(List<String> supportChannel) { InterfaceVersion.this.supportChannel = supportChannel; return this; }
        public Builder usageCondition(List<Reference<? extends InterfaceVersionUsageCondition>> usageCondition) { InterfaceVersion.this.usageCondition = usageCondition; return this; }
        public Builder versionIdentifier(String versionIdentifier) { InterfaceVersion.this.versionIdentifier = versionIdentifier; return this; }
        public Builder versionSpecification(String versionSpecification) { InterfaceVersion.this.versionSpecification = versionSpecification; return this; }
        

        public InterfaceVersion build(OpenMINDSContext context) {
            InterfaceVersion.super.build(context);
            return InterfaceVersion.this;
        }
    }

    public static InterfaceVersion.Builder create(LocalId localId){
        return new InterfaceVersion(localId).new Builder();
    }

    public InterfaceVersion.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, InterfaceVersion.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/accessibility")
    private Reference<Accessibility> accessibility;
    
    /**
    * Level to which something is accessible to someone or something.
    */
    public Reference<Accessibility> getAccessibility() {
       return this.accessibility;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contribution")
    private List<Contribution> contribution;
    
    public List<Contribution> getContribution() {
       return this.contribution;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contributorAffiliation")
    private List<Affiliation> contributorAffiliation;
    
    public List<Affiliation> getContributorAffiliation() {
       return this.contributorAffiliation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/copyright")
    private Copyright copyright;
    
    /**
    * Exclusive and assignable legal right of an originator to reproduce, publish, sell, or distribute the matter and form of a creative work for a defined time period.
    */
    public Copyright getCopyright() {
       return this.copyright;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/documentation")
    private Reference<? extends InterfaceVersionDocumentation> documentation;
    
    public Reference<? extends InterfaceVersionDocumentation> getDocumentation() {
       return this.documentation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/fullName")
    private String fullName;
    
    /**
    * Whole, non-abbreviated name of something or somebody.
    */
    public String getFullName() {
       return this.fullName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/funding")
    private List<Reference<Funding>> funding;
    
    /**
    * Money provided by a legal person for a particular purpose.
    */
    public List<Reference<Funding>> getFunding() {
       return this.funding;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/homepage")
    private String homepage;
    
    /**
    * Main website of something or someone.
    */
    public String getHomepage() {
       return this.homepage;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/howToCite")
    private String howToCite;
    
    /**
    * Preferred format for citing a particular object or legal person.
    */
    public String getHowToCite() {
       return this.howToCite;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isPrecededBy")
    private Reference<InterfaceVersion> isPrecededBy;
    
    public Reference<InterfaceVersion> getIsPrecededBy() {
       return this.isPrecededBy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVariantOf")
    private List<Reference<InterfaceVersion>> isVariantOf;
    
    public List<Reference<InterfaceVersion>> getIsVariantOf() {
       return this.isVariantOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVersionOf")
    private Reference<Interface> isVersionOf;
    
    public Reference<Interface> getIsVersionOf() {
       return this.isVersionOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/keyword")
    private List<Reference<? extends InterfaceVersionKeyword>> keyword;
    
    /**
    * Significant word or concept that are representative of something or someone.
    */
    public List<Reference<? extends InterfaceVersionKeyword>> getKeyword() {
       return this.keyword;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/publicationStatus")
    private Reference<PublicationStatus> publicationStatus;
    
    public Reference<PublicationStatus> getPublicationStatus() {
       return this.publicationStatus;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/relatedPublication")
    private List<Reference<? extends InterfaceVersionRelatedPublication>> relatedPublication;
    
    /**
    * Reference to something that was made available for the general public to see or buy.
    */
    public List<Reference<? extends InterfaceVersionRelatedPublication>> getRelatedPublication() {
       return this.relatedPublication;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/releaseDate")
    private String releaseDate;
    
    /**
    * Fixed date on which a product is due to become or was made available for the general public to see or buy
    */
    public String getReleaseDate() {
       return this.releaseDate;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/repository")
    private Reference<FileRepository> repository;
    
    /**
    * Place, room, or container where something is deposited or stored.
    */
    public Reference<FileRepository> getRepository() {
       return this.repository;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/shortName")
    private String shortName;
    
    /**
    * Shortened or fully abbreviated name of something or somebody.
    */
    public String getShortName() {
       return this.shortName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/specification")
    private Reference<? extends InterfaceVersionSpecification> specification;
    
    /**
    * Detailed and precise presentation of, or proposal for something.
    */
    public Reference<? extends InterfaceVersionSpecification> getSpecification() {
       return this.specification;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/supportChannel")
    private List<String> supportChannel;
    
    /**
    * Way of communication used to interact with users or customers.
    */
    public List<String> getSupportChannel() {
       return this.supportChannel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/usageCondition")
    private List<Reference<? extends InterfaceVersionUsageCondition>> usageCondition;
    
    public List<Reference<? extends InterfaceVersionUsageCondition>> getUsageCondition() {
       return this.usageCondition;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionIdentifier")
    private String versionIdentifier;
    
    /**
    * Term or code used to identify the version of something.
    */
    public String getVersionIdentifier() {
       return this.versionIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionSpecification")
    private String versionSpecification;
    
    public String getVersionSpecification() {
       return this.versionSpecification;
    }

 

}