package org.openmetadatainitiative.openminds.v5.core.products;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmetadatainitiative.openminds.utils.*;
import java.util.function.Function;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.openmetadatainitiative.openminds.v5.controlledTerms.Language;
import org.openmetadatainitiative.openminds.v5.controlledTerms.OperatingDevice;
import org.openmetadatainitiative.openminds.v5.controlledTerms.OperatingSystem;
import org.openmetadatainitiative.openminds.v5.controlledTerms.ProgrammingLanguage;
import org.openmetadatainitiative.openminds.v5.controlledTerms.PublicationStatus;
import org.openmetadatainitiative.openminds.v5.core.actors.Affiliation;
import org.openmetadatainitiative.openminds.v5.core.actors.Contribution;
import org.openmetadatainitiative.openminds.v5.core.data.ContentType;
import org.openmetadatainitiative.openminds.v5.core.data.Copyright;
import org.openmetadatainitiative.openminds.v5.core.data.FileRepository;
import org.openmetadatainitiative.openminds.v5.core.miscellaneous.Accessibility;
import org.openmetadatainitiative.openminds.v5.core.miscellaneous.Dependency;
import org.openmetadatainitiative.openminds.v5.core.miscellaneous.Funding;
import org.openmetadatainitiative.openminds.v5.core.products.InterfaceVersion;
import org.openmetadatainitiative.openminds.v5.core.products.Software;
import org.openmetadatainitiative.openminds.v5.core.products.SoftwareVersion;
import org.openmetadatainitiative.openminds.v5.core.products.intf.SoftwareVersionDigitalIdentifier;
import org.openmetadatainitiative.openminds.v5.core.products.intf.SoftwareVersionDocumentation;
import org.openmetadatainitiative.openminds.v5.core.products.intf.SoftwareVersionKeyword;
import org.openmetadatainitiative.openminds.v5.core.products.intf.SoftwareVersionRelatedPublication;
import org.openmetadatainitiative.openminds.v5.core.products.intf.SoftwareVersionScope;
import org.openmetadatainitiative.openminds.v5.core.products.intf.SoftwareVersionUsageCondition;


import static org.openmetadatainitiative.openminds.v5.core.products.SoftwareVersion.SEMANTIC_NAME;
/**
 * 
 *
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@InstanceType(SEMANTIC_NAME)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("unused")
public class SoftwareVersion extends Instance implements org.openmetadatainitiative.openminds.OpenMINDS.V5.Entity, org.openmetadatainitiative.openminds.v5.computation.intf.ModelValidationInput, org.openmetadatainitiative.openminds.v5.computation.intf.GenericComputationInput, org.openmetadatainitiative.openminds.v5.computation.intf.WorkflowRecipeVersionHasPart, org.openmetadatainitiative.openminds.v5.computation.intf.DataAnalysisInput, org.openmetadatainitiative.openminds.v5.computation.intf.OptimizationInput, org.openmetadatainitiative.openminds.v5.computation.intf.DataCopyInput, org.openmetadatainitiative.openminds.v5.computation.intf.SimulationInput, org.openmetadatainitiative.openminds.v5.computation.intf.ServiceDeploymentDependsOn, org.openmetadatainitiative.openminds.v5.computation.intf.VisualizationInput, org.openmetadatainitiative.openminds.v5.publications.intf.LearningResourceAbout, org.openmetadatainitiative.openminds.v5.publications.intf.LivePaperVersionAbout, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.DependencyFulfilledBy, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.CommentAbout, org.openmetadatainitiative.openminds.v5.core.miscellaneous.intf.ResearchProductGroupHasPart, org.openmetadatainitiative.openminds.v5.core.products.intf.ProjectHasPart, org.openmetadatainitiative.openminds.v5.core.products.intf.SetupHasPart{
    public static final String SEMANTIC_NAME = "https://openminds.om-i.org/types/SoftwareVersion";

    @JsonIgnore
    public Reference<SoftwareVersion> getReference() {
        return doGetReference();
    }

    public static Reference<SoftwareVersion> reference(String instanceId) {
        return new Reference<>(new InstanceId(instanceId));
    }

    /** For deserialization **/
    private SoftwareVersion() {
        this(null);
    }

    private SoftwareVersion(LocalId localId ) {
        super(localId, SEMANTIC_NAME);
    }

    

    
    public class Builder implements org.openmetadatainitiative.openminds.utils.Builder<SoftwareVersion>{
        public Builder accessibility(Reference<Accessibility> accessibility) { SoftwareVersion.this.accessibility = accessibility; return this; }
        public Builder contribution(List<Function<Contribution.EmbeddedBuilder, Contribution>> contribution) { SoftwareVersion.this.contribution = contribution.stream().map(b -> b.apply(Contribution.createEmbedded())).toList(); return this; }
        public Builder contributorAffiliation(List<Function<Affiliation.EmbeddedBuilder, Affiliation>> contributorAffiliation) { SoftwareVersion.this.contributorAffiliation = contributorAffiliation.stream().map(b -> b.apply(Affiliation.createEmbedded())).toList(); return this; }
        public Builder copyright(Function<Copyright.EmbeddedBuilder, Copyright> copyright) { SoftwareVersion.this.copyright = copyright.apply(Copyright.createEmbedded()); return this; }
        public Builder dependency(List<Function<Dependency.EmbeddedBuilder, Dependency>> dependency) { SoftwareVersion.this.dependency = dependency.stream().map(b -> b.apply(Dependency.createEmbedded())).toList(); return this; }
        public Builder description(String description) { SoftwareVersion.this.description = description; return this; }
        public Builder digitalIdentifier(Reference<? extends SoftwareVersionDigitalIdentifier> digitalIdentifier) { SoftwareVersion.this.digitalIdentifier = digitalIdentifier; return this; }
        public Builder documentation(Reference<? extends SoftwareVersionDocumentation> documentation) { SoftwareVersion.this.documentation = documentation; return this; }
        public Builder fullName(String fullName) { SoftwareVersion.this.fullName = fullName; return this; }
        public Builder funding(List<Reference<Funding>> funding) { SoftwareVersion.this.funding = funding; return this; }
        public Builder homepage(String homepage) { SoftwareVersion.this.homepage = homepage; return this; }
        public Builder howToCite(String howToCite) { SoftwareVersion.this.howToCite = howToCite; return this; }
        public Builder implements(List<Reference<InterfaceVersion>> implements) { SoftwareVersion.this.implements = implements; return this; }
        public Builder inputFormat(List<Reference<ContentType>> inputFormat) { SoftwareVersion.this.inputFormat = inputFormat; return this; }
        public Builder isPrecededBy(Reference<SoftwareVersion> isPrecededBy) { SoftwareVersion.this.isPrecededBy = isPrecededBy; return this; }
        public Builder isVariantOf(List<Reference<SoftwareVersion>> isVariantOf) { SoftwareVersion.this.isVariantOf = isVariantOf; return this; }
        public Builder isVersionOf(Reference<Software> isVersionOf) { SoftwareVersion.this.isVersionOf = isVersionOf; return this; }
        public Builder keyword(List<Reference<? extends SoftwareVersionKeyword>> keyword) { SoftwareVersion.this.keyword = keyword; return this; }
        public Builder language(List<Reference<Language>> language) { SoftwareVersion.this.language = language; return this; }
        public Builder operatingDevice(List<Reference<OperatingDevice>> operatingDevice) { SoftwareVersion.this.operatingDevice = operatingDevice; return this; }
        public Builder operatingSystem(List<Reference<OperatingSystem>> operatingSystem) { SoftwareVersion.this.operatingSystem = operatingSystem; return this; }
        public Builder outputFormat(List<Reference<ContentType>> outputFormat) { SoftwareVersion.this.outputFormat = outputFormat; return this; }
        public Builder programmingLanguage(List<Reference<ProgrammingLanguage>> programmingLanguage) { SoftwareVersion.this.programmingLanguage = programmingLanguage; return this; }
        public Builder publicationStatus(Reference<PublicationStatus> publicationStatus) { SoftwareVersion.this.publicationStatus = publicationStatus; return this; }
        public Builder relatedPublication(List<Reference<? extends SoftwareVersionRelatedPublication>> relatedPublication) { SoftwareVersion.this.relatedPublication = relatedPublication; return this; }
        public Builder releaseDate(String releaseDate) { SoftwareVersion.this.releaseDate = releaseDate; return this; }
        public Builder repository(Reference<FileRepository> repository) { SoftwareVersion.this.repository = repository; return this; }
        public Builder scope(List<Reference<? extends SoftwareVersionScope>> scope) { SoftwareVersion.this.scope = scope; return this; }
        public Builder shortName(String shortName) { SoftwareVersion.this.shortName = shortName; return this; }
        public Builder supportChannel(List<String> supportChannel) { SoftwareVersion.this.supportChannel = supportChannel; return this; }
        public Builder usageCondition(List<Reference<? extends SoftwareVersionUsageCondition>> usageCondition) { SoftwareVersion.this.usageCondition = usageCondition; return this; }
        public Builder versionIdentifier(String versionIdentifier) { SoftwareVersion.this.versionIdentifier = versionIdentifier; return this; }
        public Builder versionSpecification(String versionSpecification) { SoftwareVersion.this.versionSpecification = versionSpecification; return this; }
        

        public SoftwareVersion build(OpenMINDSContext context) {
            SoftwareVersion.super.build(context);
            return SoftwareVersion.this;
        }
    }

    public static SoftwareVersion.Builder create(LocalId localId){
        return new SoftwareVersion(localId).new Builder();
    }

    public SoftwareVersion.Builder copy(){
        return ParsingUtils.OBJECT_MAPPER.convertValue(this, SoftwareVersion.class).new Builder();
    }
    

   @JsonProperty(value = "https://openminds.om-i.org/props/accessibility")
    private Reference<Accessibility> accessibility;
    
    /**
    * Level to which something is accessible to someone or something.
    */
    public Reference<Accessibility> getAccessibility() {
       return this.accessibility;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contribution")
    private List<Contribution> contribution;
    
    public List<Contribution> getContribution() {
       return this.contribution;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/contributorAffiliation")
    private List<Affiliation> contributorAffiliation;
    
    public List<Affiliation> getContributorAffiliation() {
       return this.contributorAffiliation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/copyright")
    private Copyright copyright;
    
    /**
    * Exclusive and assignable legal right of an originator to reproduce, publish, sell, or distribute the matter and form of a creative work for a defined time period.
    */
    public Copyright getCopyright() {
       return this.copyright;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/dependency")
    private List<Dependency> dependency;
    
    public List<Dependency> getDependency() {
       return this.dependency;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/description")
    private String description;
    
    /**
    * Longer statement or account giving the characteristics of someone or something.
    */
    public String getDescription() {
       return this.description;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/digitalIdentifier")
    private Reference<? extends SoftwareVersionDigitalIdentifier> digitalIdentifier;
    
    /**
    * Digital handle to identify objects or legal persons.
    */
    public Reference<? extends SoftwareVersionDigitalIdentifier> getDigitalIdentifier() {
       return this.digitalIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/documentation")
    private Reference<? extends SoftwareVersionDocumentation> documentation;
    
    public Reference<? extends SoftwareVersionDocumentation> getDocumentation() {
       return this.documentation;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/fullName")
    private String fullName;
    
    /**
    * Whole, non-abbreviated name of something or somebody.
    */
    public String getFullName() {
       return this.fullName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/funding")
    private List<Reference<Funding>> funding;
    
    /**
    * Money provided by a legal person for a particular purpose.
    */
    public List<Reference<Funding>> getFunding() {
       return this.funding;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/homepage")
    private String homepage;
    
    /**
    * Main website of something or someone.
    */
    public String getHomepage() {
       return this.homepage;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/howToCite")
    private String howToCite;
    
    /**
    * Preferred format for citing a particular object or legal person.
    */
    public String getHowToCite() {
       return this.howToCite;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/implements")
    private List<Reference<InterfaceVersion>> implements;
    
    public List<Reference<InterfaceVersion>> getImplements() {
       return this.implements;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/inputFormat")
    private List<Reference<ContentType>> inputFormat;
    
    /**
    * Format of data that is put into a process or machine.
    */
    public List<Reference<ContentType>> getInputFormat() {
       return this.inputFormat;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isPrecededBy")
    private Reference<SoftwareVersion> isPrecededBy;
    
    public Reference<SoftwareVersion> getIsPrecededBy() {
       return this.isPrecededBy;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVariantOf")
    private List<Reference<SoftwareVersion>> isVariantOf;
    
    public List<Reference<SoftwareVersion>> getIsVariantOf() {
       return this.isVariantOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/isVersionOf")
    private Reference<Software> isVersionOf;
    
    public Reference<Software> getIsVersionOf() {
       return this.isVersionOf;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/keyword")
    private List<Reference<? extends SoftwareVersionKeyword>> keyword;
    
    /**
    * Significant word or concept that are representative of something or someone.
    */
    public List<Reference<? extends SoftwareVersionKeyword>> getKeyword() {
       return this.keyword;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/language")
    private List<Reference<Language>> language;
    
    /**
    * System of communication (words, their pronunciation, and the methods of combining them) used and understood by a particular community.
    */
    public List<Reference<Language>> getLanguage() {
       return this.language;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/operatingDevice")
    private List<Reference<OperatingDevice>> operatingDevice;
    
    public List<Reference<OperatingDevice>> getOperatingDevice() {
       return this.operatingDevice;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/operatingSystem")
    private List<Reference<OperatingSystem>> operatingSystem;
    
    /**
    * Software that controls the operation of a computer and directs the processing of programs.
    */
    public List<Reference<OperatingSystem>> getOperatingSystem() {
       return this.operatingSystem;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/outputFormat")
    private List<Reference<ContentType>> outputFormat;
    
    /**
    * Format of data that comes out of, is delivered or produced by a process or machine.
    */
    public List<Reference<ContentType>> getOutputFormat() {
       return this.outputFormat;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/programmingLanguage")
    private List<Reference<ProgrammingLanguage>> programmingLanguage;
    
    /**
    * Distinct set of instructions for computer programs in order to produce various kinds of output.
    */
    public List<Reference<ProgrammingLanguage>> getProgrammingLanguage() {
       return this.programmingLanguage;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/publicationStatus")
    private Reference<PublicationStatus> publicationStatus;
    
    public Reference<PublicationStatus> getPublicationStatus() {
       return this.publicationStatus;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/relatedPublication")
    private List<Reference<? extends SoftwareVersionRelatedPublication>> relatedPublication;
    
    /**
    * Reference to something that was made available for the general public to see or buy.
    */
    public List<Reference<? extends SoftwareVersionRelatedPublication>> getRelatedPublication() {
       return this.relatedPublication;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/releaseDate")
    private String releaseDate;
    
    /**
    * Fixed date on which a product is due to become or was made available for the general public to see or buy
    */
    public String getReleaseDate() {
       return this.releaseDate;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/repository")
    private Reference<FileRepository> repository;
    
    /**
    * Place, room, or container where something is deposited or stored.
    */
    public Reference<FileRepository> getRepository() {
       return this.repository;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/scope")
    private List<Reference<? extends SoftwareVersionScope>> scope;
    
    /**
    * Extent of something.
    */
    public List<Reference<? extends SoftwareVersionScope>> getScope() {
       return this.scope;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/shortName")
    private String shortName;
    
    /**
    * Shortened or fully abbreviated name of something or somebody.
    */
    public String getShortName() {
       return this.shortName;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/supportChannel")
    private List<String> supportChannel;
    
    /**
    * Way of communication used to interact with users or customers.
    */
    public List<String> getSupportChannel() {
       return this.supportChannel;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/usageCondition")
    private List<Reference<? extends SoftwareVersionUsageCondition>> usageCondition;
    
    public List<Reference<? extends SoftwareVersionUsageCondition>> getUsageCondition() {
       return this.usageCondition;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionIdentifier")
    private String versionIdentifier;
    
    /**
    * Term or code used to identify the version of something.
    */
    public String getVersionIdentifier() {
       return this.versionIdentifier;
    }

    @JsonProperty(value = "https://openminds.om-i.org/props/versionSpecification")
    private String versionSpecification;
    
    public String getVersionSpecification() {
       return this.versionSpecification;
    }

 

}