package org.openmetadatainitiative.openminds.latest.chemicals.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
public interface AmountOfChemicalChemicalProduct extends Entity {
   Reference<? extends AmountOfChemicalChemicalProduct> getReference();

   class Deserializer extends ByTypeDeserializer<AmountOfChemicalChemicalProduct> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.latest.chemicals.ChemicalMixture.class, org.openmetadatainitiative.openminds.latest.chemicals.ChemicalSubstance.class, org.openmetadatainitiative.openminds.latest.controlledTerms.MolecularEntity.class);
        }
    }
}