package org.openmetadatainitiative.openminds.latest.ephys.device.intf;

import org.openmetadatainitiative.openminds.utils.ByTypeDeserializer;
import org.openmetadatainitiative.openminds.utils.Entity;
import org.openmetadatainitiative.openminds.utils.Reference;

/**
 * ATTENTION! This is an autogenerated file based on the openMINDS schema - do not apply manual changes since they are going to be overwritten.
 */
@SuppressWarnings("unused")
public interface PipetteType extends Entity {
   Reference<? extends PipetteType> getReference();

   class Deserializer extends ByTypeDeserializer<PipetteType> {
        public Deserializer() {
            super(org.openmetadatainitiative.openminds.latest.controlledTerms.DeviceType.class, org.openmetadatainitiative.openminds.latest.core.products.HardwareProduct.class);
        }
    }
    
}